parameters:
- name: ResourceGroupName
  type: string
- name: Subscription
  type: string
- name: TemplateFile
  type: string
- name: SQLDatabaseName
  type: string
- name: SQLServerAdminUsername
  type: string
- name: SQLServerAdminPassword
  type: string
- name: DacPacLocation
  type: string
- name: ConfigPath
  type: string
- name: ConfigTargetFilename
  type: string
- name: ConfigStorageAccountName
  type: string
# - name: EnvironmentNameAbbreviation
#   type: string
# - name: WorkerASPSize
#   type: string
# - name: WorkerASPInstances
#   type: string
# - name: SharedASPName
#   type: string
# - name: SharedEnvResourceGroupName
#   type: string
# - name: SharedKeyVaultName
#   type: string
# - name: SharedSQLServerName
#   type: string

# - name: SQLDatabaseSkuName
#   type: string
# - name: SQLDatabaseTier
#   type: string
# - name: ConfigurationStorageConnectionString
#   type: securestring
# - name: UICustomHostName
#   type: string
# - name: CertificateName
#   type: string
# - name: EmployerFeedbackTrigger
#   type: string
# - name: ProviderFeedbackTrigger
#   type: string
# - name: ProviderReferenceTrigger
#   type: string

steps:
- task: AzureResourceGroupDeployment@2
  displayName: 'Azure Deployment:Create Or Update Resource Group action on ${{parameters.ResourceGroupName}}'
  inputs:
    azureSubscription: '${{parameters.Subscription}}'
    resourceGroupName: '${{parameters.ResourceGroupName}}'
    location: 'West Europe'
    csmFile: '${{parameters.TemplateFile}}'
    overrideParameters: '-environmentNameAbbreviation "${{parameters.EnvironmentNameAbbreviation}}" -workerASPSize "${{parameters.WorkerASPSize}}" -workerASPInstances "${{parameters.WorkerASPInstances}}" -sharedASPName "${{parameters.SharedASPName}}" -sharedEnvResourceGroup "${{parameters.SharedEnvResourceGroupName}}" -sharedKeyVaultName "${{parameters.SharedKeyVaultName}}" -sharedSQLServerName "${{parameters.SharedSQLServerName}}" -sqlDatabaseSkuName "${{parameters.SQLDatabaseSkuName}}" -sqlDatabaseTier "${{parameters.SQLDatabaseTier}}" -configurationStorageConnectionString "${{parameters.ConfigurationStorageConnectionString}}" -uiCustomHostName "${{parameters.UICustomHostName}}" -certificateName "${{parameters.CertificateName}}" -employerFeedbackTrigger "${{parameters.EmployerFeedbackTrigger}}" -providerFeedbackTrigger "${{parameters.ProviderFeedbackTrigger}}" -providerReferenceTrigger "${{parameters.ProviderReferenceTrigger}}"'
    deploymentOutputs: armOutputs

- task: ARMTemplateOutputs@0
  displayName: 'Convert ARM Template Outputs to Variables'
  inputs:
    ARMOutputs: '$(armOutputs)'

- task: GenerateEnvironmentConfiguration@3
  displayName: 'Process schemas in ${{parameters.ConfigPath}}'
  inputs:
    SourcePath: '${{parameters.ConfigPath}}'
    TargetFilename: ${{parameters.ConfigTargetFilename}}
    ServiceConnectionName: '${{parameters.Subscription}}'
    StorageAccountName: '${{parameters.ConfigStorageAccountName}}'
    TableName: Configuration

- task: SqlAzureDacpacDeployment@1
  displayName: 'Azure SQL Publish'
  inputs:
    azureSubscription: '${{parameters.Subscription}}'
    ServerName: '${{parameters.SharedSQLServerName}}.database.windows.net'
    DatabaseName: '${{parameters.SQLDatabaseName}}'
    SqlUsername: '${{parameters.SQLServerAdminUsername}}'
    SqlPassword: '${{parameters.SQLServerAdminPassword}}'
    DacpacFile: '${{parameters.DacPacLocation}}'
    AdditionalArguments: '/p:GenerateSmartDefaults=True'