stages:
#Build
  - template: matching-build-stage.yml  
  - template: matching-shared-infrastructure-stage.yml

  - template: matching-deploy-infrastructure-stage.yml
    parameters:
      stageName: Dev
      dependencies:
      - build
      - sharedInfrastructure
      environmentName: dev
      environmentId: d01 
 
  - template: matching-infrastructure-stage.yml
    parameters:
      stageName: Test
      dependencies: 
      - Deploy_Dev
      environmentName: test
      environmentId: t01

  
  #deploy at
  # - stage: deployAT

  #   variables:
  #   #s126d01-dev-matching
  #     SQLServerActiveDirectoryAdminLogin: 'TL DEV SQL ADM'
  #     SQLServerActiveDirectoryAdminObjectId: '56f27acd-6ea8-4526-a25c-29436d62826c'
  #     ThreatDetectionEmailAddress: 'tlevelsdevops@education.gov.uk'
  #     AppServicePlanTier: 'Standard'
  #     AppServicePlanSize: '1'
  #     AppServicePlanInstances: '2'
  #     AzureWebsitesRPObjectId: '0b11c7a6-2868-4728-b83c-d14be9147a97' # s126-tlevelservice-Reader USR
  #     KeyVaultReadWriteObjectIds: '["56f27acd-6ea8-4526-a25c-29436d62826c"]' # s126-tlevelservice-Managers USR, 
  #     keyVaultFullAccessObjectIds: '["0316d3ae-e503-4dae-9665-c999fca7cf10", "a6621090-e704-45ec-b65f-50257f9d4dcd"]'
  #     SharedResourceGroup: 's126d01-matching-shared'
  #     CertificateName: 'wildcard-industryplacementmatching-education-gov-uk'
  #     UICustomHostName: '' #'dev.industryplacementmatching.education.gov.uk'    
  #     ResourceGroupName: 's126d01-matching'
  #     WorkerASPSize: '1'
  #     WorkerASPInstances: '1'
  #     SQLDatabaseSkuName: 'S0'
  #     SQLDatabaseTier: 'Standard'
  #     BankHolidayGeneratorTrigger: '0 45 9  * * WED'
  #     EmployerFeedbackTrigger: '0 0 9 * * MON-FRI'
  #     ProviderFeedbackTrigger: '0 0 9 * * MON-FRI'
  #     ProviderReferenceTrigger: '0 0 7 * * *'

  #     applicationName: matching
  #     buildConfiguration: 'release'
  #     buildPlatform: 'anycpu'      
  #     SharedEnvResourceGroupName: 's126d01-matching-shared'
  #     SharedSQLServerName: 's126d01-matching-shared-001-sqlsvr'
  #     testSqlDatabaseSkuName: 'S0'
  #     testSqlDatabaseTier: 'Standard'
  #     ConfigStorageAccountName: 's126d01matchingconfigstr'
  #     dotnetVersion: '3.x'      
  #     workerASPInstances: 1      
  #   jobs:

  #   - template: ../jobs/matching-shared-infrastructure.yml
  #     parameters:
  #       environmentId: d01

  #   - template: ../jobs/matching-infrastructure.yml
  #     parameters:
  #       SharedInfrastructureDependency: DeploySharedInfrastructure
  #       SharedEnvResourceGroupName: $(SharedResourceGroup)
  #       UICustomHostName: $(UICustomHostName)
  #       CertificateName: $(CertificateName)
  #       ResourceGroupName: $(ResourceGroupName)
    
  #   - job: TagResouceGroup
  #     dependsOn: 
  #       - DeploySharedInfrastructure
  #       - DeployMatchingInfrastructure
  #     steps:
  #     - task: AzurePowerShell@5
  #       inputs:
  #         azureSubscription: 'S126-TL-Dev-Service-Connection'
  #         ScriptType: 'InlineScript'
  #         Inline: |
  #           $Tags = @{'Parent Business' = 'Apprenticeships'; 'Service Offering' = 'ESFA T Level Service' }
  #           Get-AzResourceGroup | Where-Object ResourceGroupName -Like "*matching*" | ForEach-Object {
  #               Update-AzTag -ResourceId $_.ResourceId -Tag $Tags -Operation Merge   
  #           }
  #         azurePowerShellVersion: 'LatestVersion'
  #         pwsh: true

  #   # - template: ../jobs/matching-deploy.yml