parameters:
- name: stageName
  type: string
- name: dependencies
  type: object
- name: environmentName
  type: string
- name: environmentId
  type: string
- name: sharedEnvironmentId
  type: string
- name: variableGroups
  type: object
- name: serviceConnection
  type: string

stages:
- stage: Deploy_${{parameters.environmentId}}
  dependsOn: 
    - '${{ each dependency in parameters.dependencies }}':
      - '${{dependency}}'
  variables:
    - '${{ each variableGroup in parameters.variableGroups }}':
      - group: '${{variableGroup}}'
    - name: BaseName
      value: "s126${{parameters.environmentId}}-matching"
    - name: ResourceGroupName
      value: '$(BaseName)'
    - name: EnvironmentName
      value: ${{ parameters.environmentName }} 
      
      
  displayName: '${{parameters.environmentName}} [${{parameters.environmentId}}] deployment'
  jobs:  
  - template: ../jobs/matching-infrastructure-job.yml
    parameters:
      BaseName: $(BaseName)
      serviceConnection: ${{ parameters.serviceConnection }}
      sharedEnvironmentId: ${{ parameters.sharedEnvironmentId }}
      
  - template: ../jobs/matching-publish-site-job.yml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}