stages:
  - stage: AT_Deploy
    variables:
      SQLServerActiveDirectoryAdminLogin: 'TL DEV SQL ADM'
      SQLServerActiveDirectoryAdminObjectId: 'ede7deec-20a1-44ac-b5e0-289f5531ff59'
      ThreatDetectionEmailAddress: 'tlevelsdevops@education.gov.uk'
      AppServicePlanTier: 'Standard'
      AppServicePlanSize: '1'
      AppServicePlanInstances: '2'
      AzureWebsitesRPObjectId: '7fa23fd6-537e-4d28-b0ca-54d075cce842'
      KeyVaultReadWriteObjectIds: '["94923ac5-81df-4584-8806-a69f5fae6c14"]'

    jobs:
    - job: DeploySharedInfrastructure
    #Your build pipeline references an undefined variable named ‘SQLServerAdminUsername’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
    #Your build pipeline references an undefined variable named ‘SQLServerAdminPassword’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

    steps:
    - task: AzureResourceGroupDeployment@2
      displayName: 'Azure Deployment:Create Or Update Resource Group action on $(SharedEnvResourceGroupName)'
      inputs:
        azureSubscription: 'SFA-TL-Dev/Test'
        resourceGroupName: '$(SharedEnvResourceGroupName)'
        location: 'West Europe'
        csmFile: './azure/resac-shared.json'
        overrideParameters: '-environmentNameAbbreviation "$(Release.EnvironmentName)" -sqlServerAdminUsername "$(SQLServerAdminUsername)" -sqlServerAdminPassword "$(SQLServerAdminPassword)" -sqlServerActiveDirectoryAdminLogin "$(SQLServerActiveDirectoryAdminLogin)" -sqlServerActiveDirectoryAdminObjectId "$(SQLServerActiveDirectoryAdminObjectId)" -threatDetectionEmailAddress "$(ThreatDetectionEmailAddress)" -appServicePlanTier "$(AppServicePlanTier)" -appServicePlanSize "$(AppServicePlanSize)" -appServicePlanInstances "$(AppServicePlanInstances)" -azureWebsitesRPObjectId "$(AzureWebsitesRPObjectId)" -keyVaultReadWriteObjectIds $(KeyVaultReadWriteObjectIds)'
