parameters:
- name: stageName
  type: string
- name: dependencies
  type: object
- name: environmentName
  type: string
- name: environmentId
  type: string
stages:
- stage: Deploy_${{parameters.stageName}}
  dependsOn: 
    - '${{ each dependency in parameters.dependencies }}':
      - '${{dependency}}'
  variables:
    BaseName: "s126${{parameters.environmentId}}-matching"
    ResourceGroupName: '$(BaseName)'
    SharedResourceGroup: '$(BaseName)-shared'
    SharedSQLServerName: '$(BaseName)-shared-sqlsvr'
    ConfigStorageAccountName: '$(BaseName)configstr'
  
      
  displayName: '${{parameters.environmentName}} [${{parameters.environmentId}}]'
  jobs:
  - template: ../jobs/matching-shared-infrastructure-job.yml
    parameters:
      baseName: $(BaseName)
  
  - template: ../jobs/matching-infrastructure-job.yml
    parameters:
      BaseName: $(BaseName)
  
  - template: ../jobs/matching-publish-site-job.yml