parameters:
- name: stageName
  type: string
- name: dependencies
  type: object
- name: environmentName
  type: string
- name: environmentId
  type: string
stages:
- stage: Deploy_${{parameters.stageName}}
  dependsOn: 
    - '${{ each dependency in parameters.dependencies }}':
      - '${{dependency}}'
  variables:
    ResourceGroupName: 's126${{parameters.environmentId}}-matching'
    SharedEnvResourceGroupName: 's126${{parameters.environmentId}}-matching-shared'
    SharedSQLServerName: 's126${{parameters.environmentId}}-matching-shared-sqlsvr'
    ConfigStorageAccountName: 's126${{parameters.environmentId}}matchingconfigstr'
  
      
  displayName: '${{parameters.environmentName}} [${{parameters.environmentId}}]'
  jobs:
  - template: ../jobs/matching-shared-infrastructure-job.yml
    parameters:
      environmentId: ${{parameters.environmentId}}
  
  - template: ../jobs/matching-infrastructure-job.yml
    parameters:
      environmentNameAbbreviation: $(ResouceGroupName)
  
  - template: ../jobs/matching-publish-site-job.yml