stages:
  #Build
  - stage: start
    jobs:
      - job: start
        steps:
          - pwsh: Write-Host "Starting"

  - template: matching-build-stage.yml
    parameters:
      dependencies:
        - start
######################## DEV ##############################################
  - template: matching-shared-stage.yml
    parameters:
      stageName: Dev
      dependencies:
        - build
      environmentName: dev
      sharedEnvironmentId: d01
      variableGroups:
        - platform-dev
        - platform-dev-matching
      serviceConnection: $(devServiceConnection)
    
  - template: matching-stage.yml
    parameters:
      stageName: Dev
      dependencies:
        - DeploySharedInfrastructure_d01
      environmentName: dev
      environmentId: d01
      sharedEnvironmentId: d01
      variableGroups:
        - platform-dev
        - platform-dev-matching
        - platform-global-matching
      serviceConnection: $(devServiceConnection)


######################## TEST ##############################################
  - template: matching-shared-stage.yml
    parameters:
      stageName: Test
      dependencies:
        - DeploySharedInfrastructure_d01
        - Deploy_d01
      environmentName: test
      sharedEnvironmentId: t01
      variableGroups:
        - platform-test
        - platform-test-matching
      serviceConnection: $(testServiceConnection)
    
  - template: matching-stage.yml
    parameters:
      stageName: Test
      dependencies:
        - DeploySharedInfrastructure_t01
      environmentName: test
      environmentId: t01
      sharedEnvironmentId: t01
      variableGroups:
        - platform-test
        - platform-test-matching
      serviceConnection: $(testServiceConnection)

######################## Pre Prod ##############################################
  - template: matching-shared-stage.yml
    parameters:
      stageName: PreProd
      dependencies:
        - DeploySharedInfrastructure_t01
        - Deploy_t01
      environmentName: preprod
      sharedEnvironmentId: p02
      variableGroups:
        - platform-preprod
        - platform-preprod-matching
      serviceConnection: $(prodServiceConnection)
    
  - template: matching-stage.yml
    parameters:
      stageName: PreProd
      dependencies:
        - DeploySharedInfrastructure_p02
      environmentName: preprod
      environmentId: p02
      sharedEnvironmentId: p02
      variableGroups:
        - platform-preprod
        - platform-preprod-matching
      serviceConnection: $(prodServiceConnection)

# ######################## Prod ##############################################
  - template: matching-shared-stage.yml
    parameters:
      stageName: Prod
      dependencies:
        - Deploy_p02
      environmentName: prod
      sharedEnvironmentId: p01
      variableGroups:
        - platform-prod
        - platform-prod-matching
      serviceConnection: $(prodServiceConnection)
    
  - template: matching-stage.yml
    parameters:
      stageName: Prod
      dependencies:
        - DeploySharedInfrastructure_p01
      environmentName: prod
      environmentId: p01
      sharedEnvironmentId: p01
      variableGroups:
        - platform-prod
        - platform-prod-matching
      serviceConnection: $(prodServiceConnection)