parameters:
- name: stageName
  type: string
- name: dependencyName
  type: string
- name: environmentName
  type: string
- name: environmentId
  type: string
stages:
- stage: Publish_${{parameters.stageName}}
  dependsOn: '${{parameters.dependencyName}}'
  displayName: 'Publishing matching site ${{parameters.environmentName}} [${{parameters.environmentId}}]'
  jobs:
    - template: ../jobs/matching-publish-site-job.yml
