parameters:
- name: stageName
  type: string
- name: dependencies
  type: object
- name: environmentName
  type: string
- name: environmentId
  type: string
stages:
- stage: Deploy_${{parameters.stageName}}
  dependsOn: 
    - '${{ each dependency in parameters.dependencies }}':
      - '${{dependency}}'
      
  displayName: '${{parameters.environmentName}} [${{parameters.environmentId}}]'
  jobs:
  - template: ../jobs/matching-shared-infrastructure-job.yml
  - template: ../jobs/matching-infrastructure-job.yml
  - template: ../jobs/matching-publish-site-job.yml
