parameters:
- name: dependencies
  type: object
stages:
- stage: build
  dependsOn: 
    - '${{ each dependency in parameters.dependencies }}':
      - '${{dependency}}'
  # jobs:
  # - template: ../jobs/matching-build-application-job.yml
  # - template: ../jobs/matching-build-dacpac-job.yml
