parameters:
- name: stageName
  type: string
- name: dependencies
  type: object
- name: environmentName
  type: string
- name: environmentId
  type: string
- name: variableGroups
  type: object
- name: serviceConnection
  type: string
stages:
- stage: Deploy_${{parameters.environmentId}}
  dependsOn: 
    - '${{ each dependency in parameters.dependencies }}':
      - '${{dependency}}'
  variables:
    - '${{ each variableGroup in parameters.variableGroups }}':
      - group: '${{variableGroup}}'
    - name: BaseName
      value: "s126${{parameters.environmentId}}-matching"
    - name: SharedBaseName
      value: "s126${{parameters.sharedEnvironmentId}}-matching"
    - name: ResourceGroupName
      value: '$(BaseName)'
    - name: SharedResourceGroup
      value: '$(SharedBaseName)-shared'
    - name: SharedSQLServerName
      value: '$(SharedBaseName)-shared-sqlsvr'
    - name: ConfigStorageAccountName
      value: '$(BaseName)configstr'
  
      
  displayName: '${{parameters.environmentName}} [${{parameters.environmentId}}]'
  jobs:
  - template: ../jobs/matching-shared-infrastructure-job.yml
    parameters:
      baseName: $(SharedBaseName)
      serviceConnection: ${{ parameters.serviceConnection }}

  
  # - template: ../jobs/matching-infrastructure-job.yml
  #   parameters:
  #     BaseName: $(BaseName)
  #     serviceConnection: ${{ parameters.serviceConnection }}

  
  # - template: ../jobs/matching-publish-site-job.yml