stages:
#Build
  - template: matching-build-stage.yml  
  - template: matching-shared-infrastructure-stage.yml

  - template: matching-infrastructure-stage.yml
    parameters:
      stageName: Dev
      dependencies:
      - build
      - sharedInfrastructure
      environmentName: dev
      environmentId: d01 
 
  - template: matching-infrastructure-stage.yml
    parameters:
      stageName: Test
      dependencies: 
      - Deploy_Dev
      environmentName: test
      environmentId: t01


  - template: matching-infrastructure-stage.yml
    parameters:
      stageName: PreProd
      dependencies: 
      - Deploy_Test
      environmentName: Integraionf
      environmentId: t02

  
  #deploy at
  # - stage: deployAT

  #   
  #   jobs:

  #   - template: ../jobs/matching-shared-infrastructure.yml
  #     parameters:
  #       environmentId: d01

  #   - template: ../jobs/matching-infrastructure.yml
  #     parameters:
  #       SharedInfrastructureDependency: DeploySharedInfrastructure
  #       SharedEnvResourceGroupName: $(SharedResourceGroup)
  #       UICustomHostName: $(UICustomHostName)
  #       CertificateName: $(CertificateName)
  #       ResourceGroupName: $(ResourceGroupName)
    
  #   - job: TagResouceGroup
  #     dependsOn: 
  #       - DeploySharedInfrastructure
  #       - DeployMatchingInfrastructure
  #     steps:
  #     - task: AzurePowerShell@5
  #       inputs:
  #         azureSubscription: 'S126-TL-Dev-Service-Connection'
  #         ScriptType: 'InlineScript'
  #         Inline: |
  #           $Tags = @{'Parent Business' = 'Apprenticeships'; 'Service Offering' = 'ESFA T Level Service' }
  #           Get-AzResourceGroup | Where-Object ResourceGroupName -Like "*matching*" | ForEach-Object {
  #               Update-AzTag -ResourceId $_.ResourceId -Tag $Tags -Operation Merge   
  #           }
  #         azurePowerShellVersion: 'LatestVersion'
  #         pwsh: true

  #   # - template: ../jobs/matching-deploy.yml