resources:
  repositories:
    - repository: self
      persistCredentials: true
      clean: true
    # - repository: devopsTools
    #   type: github
    #   endpoint: DFE-Digital
    #   name: DFE-Digital/operations-devops-tools


    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/operations-devops-pipeline-templates

trigger:
  branches:
    include:
    - NewBuild_Core
pr: none

variables:

###### shared #####
# Resource Group
#   s126-at-TLevels
# infrastructure
# 
#   s126-at-TLevels-001-matching-kv
#   s126-at-TLevels-001-matching-config-str
#   s126-at-TLevels-001-matching-shared-str
#   s126-at-TLevels-001-matching-shared-sqlsvr
#
#application:
# Resource Group
#   s126-at-TLevels-matching
# s126-at-TLevels-matching-001-str
# s126-at-TLevels-matching-001-asp
# s126-at-TLevels-matching-001-ai
# s126-at-TLevels-matching-001-web
# s126-at-TLevels-matching-001-func
# s126-at-TLevels-matching-001-sqldb

  applicationName: matching
  buildConfiguration: 'release'
  buildPlatform: 'anycpu'
  ResourceGroupName: 'tl-at-mtch-rg'
  SharedEnvResourceGroupName: 'tl-at-shared-rg'
  SharedSQLServerName: 'tl-at-shared-sql'
  testSqlDatabaseSkuName: 'S0'
  testSqlDatabaseTier: 'Standard'
  ConfigStorageAccountName: 'tlatconfigstr'
  SQLServerAdminUsername: '7acbc5ae77f74b00a9e9'
  SQLServerAdminPassword: ''
  dotnetVersion: '3.x'
   

stages:
  - template: ./yaml/stages/matching-build.yml
