resources:
  repositories:
    - repository: self
      persistCredentials: true
      clean: true
    # - repository: devopsTools
    #   type: github
    #   endpoint: DFE-Digital
    #   name: DFE-Digital/operations-devops-tools


    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/operations-devops-pipeline-templates

trigger:
  branches:
    include:
    - NewBuild_Core
pr: none

variables:

###### shared #####
# Resource Group
#   s126-at-TLevels
# infrastructure
# 
#   s126-at-TLevels-001-matching-kv
#   s126-at-TLevels-001-matching-config-str
#   s126-at-TLevels-001-matching-shared-str
#   s126-at-TLevels-001-matching-shared-sqlsvr
#
#application:
# Resource Group
#   s126-at-TLevels-matching
# s126-at-TLevels-matching-001-str
# s126-at-TLevels-matching-001-asp
# s126-at-TLevels-matching-001-ai
# s126-at-TLevels-matching-001-web
# s126-at-TLevels-matching-001-func
# s126-at-TLevels-matching-001-sqldb

  applicationName: matching
  buildConfiguration: 'release'
  buildPlatform: 'anycpu'
  ResourceGroupName: 's126d01-matching'
  SharedEnvResourceGroupName: 's126d01-matching-shared'
  SharedSQLServerName: 's126d01-matching-shared-001-sqlsvr'
  testSqlDatabaseSkuName: 'S0'
  testSqlDatabaseTier: 'Standard'
  ConfigStorageAccountName: 's126d01matchingconfigstr'
  dotnetVersion: '3.x'
  WorkerASPSize: 1
  workerASPInstances: 1
  AppServicePlanTier: 'Standard' 

stages:
  - template: ./yaml/stages/matching-master-stage.yml

