resources:
  repositories:
    - repository: self
      persistCredentials: true
      clean: true
    # - repository: devopsTools
    #   type: github
    #   endpoint: DFE-Digital
    #   name: DFE-Digital/operations-devops-tools


    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/operations-devops-pipeline-templates

trigger:
  branches:
    include:
    - NewBuild_Core
pr: none

variables:

###### shared #####
# Resource Group
#   s126-at-TLevels
# infrastructure
# 
#   s126-at-TLevels-001-matching-kv
#   s126-at-TLevels-001-matching-config-str
#   s126-at-TLevels-001-matching-shared-str
#   s126-at-TLevels-001-matching-shared-sqlsvr
#
#application:
# Resource Group
#   s126-at-TLevels-matching
# s126-at-TLevels-matching-001-str
# s126-at-TLevels-matching-001-asp
# s126-at-TLevels-matching-001-ai
# s126-at-TLevels-matching-001-web
# s126-at-TLevels-matching-001-func
# s126-at-TLevels-matching-001-sqldb

  applicationName: matching
  buildConfiguration: 'release'
  buildPlatform: 'anycpu'
  ResourceGroupName: 's126d01-matching'
  SharedEnvResourceGroupName: 's126d01-matching-shared'
  SharedSQLServerName: 's126d01-matching-shared-001-sqlsvr'
  testSqlDatabaseSkuName: 'S0'
  testSqlDatabaseTier: 'Standard'
  ConfigStorageAccountName: 's126d01matchingconfigstr'
  dotnetVersion: '3.x'
   

stages:
  # - stage: build
  #   jobs:
  #   - template: ./yaml/jobs/matching-build.yml
  - stage: deploySharedInfrastructure
    variables:
      SQLServerActiveDirectoryAdminLogin: 'TL DEV SQL ADM'
      SQLServerActiveDirectoryAdminObjectId: 'ede7deec-20a1-44ac-b5e0-289f5531ff59'
      ThreatDetectionEmailAddress: 'tlevelsdevops@education.gov.uk'
      AppServicePlanTier: 'Standard'
      AppServicePlanSize: '1'
      AppServicePlanInstances: '2'
      AzureWebsitesRPObjectId: '7fa23fd6-537e-4d28-b0ca-54d075cce842'
      KeyVaultReadWriteObjectIds: '["94923ac5-81df-4584-8806-a69f5fae6c14"]'

    jobs:
    - template: ./yaml/jobs/matching-shared-infrastructure.yml