resources:
  repositories:
    - repository: self
      persistCredentials: true
      clean: true
    # - repository: devopsTools
    #   type: github
    #   endpoint: DFE-Digital
    #   name: DFE-Digital/operations-devops-tools
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/operations-devops-pipeline-templates

trigger:
  branches:
    include:
    - NewBuild_Core
pr: none 

stages:
  - template: ./yaml/stages/matching-master-stage.yml

