# resources:
#   repositories:
#     - repository: self
#       persistCredentials: true
#       clean: true

#     - repository: devopsTemplates
#       type: github
#       endpoint: DfE-Digital
#       name: DFE-Digital/operations-devops-pipeline-templates

# trigger:
#   branches:
#     include:
#     - NewBuild_Core
# pr: none

# variables:
#   applicationName: matching
# stages:
#   - template: ./yaml/stages/matching-master-stage.yml

