resources:
  repositories:
    - repository: self
      persistCredentials: true
      clean: true
    # - repository: devopsTools
    #   type: github
    #   endpoint: DFE-Digital
    #   name: DFE-Digital/operations-devops-tools


    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/operations-devops-pipeline-templates

trigger:
  branches:
    include:
    - NewBuild_Core
pr: none

variables:
  buildConfiguration: 'release'
  buildPlatform: 'anycpu'
  dotnetVersion: '3.x'
  SQLServerActiveDirectoryAdminLogin: 'TL DEV SQL ADM'
  SQLServerActiveDirectoryAdminObjectId: '56f27acd-6ea8-4526-a25c-29436d62826c'
  ThreatDetectionEmailAddress: 'tlevelsdevops@education.gov.uk'
  AppServicePlanTier: 'Standard'
  AppServicePlanSize: '1'
  AppServicePlanInstances: '2'
  AzureWebsitesRPObjectId: '0b11c7a6-2868-4728-b83c-d14be9147a97' # s126-tlevelservice-Reader USR
  KeyVaultReadWriteObjectIds: '["56f27acd-6ea8-4526-a25c-29436d62826c"]' # s126-tlevelservice-Managers USR, 
  keyVaultFullAccessObjectIds: '["0316d3ae-e503-4dae-9665-c999fca7cf10", "a6621090-e704-45ec-b65f-50257f9d4dcd"]'
  SharedResourceGroup: 's126d01-matching-shared'
  CertificateName: 'wildcard-industryplacementmatching-education-gov-uk'
  UICustomHostName: '' #'dev.industryplacementmatching.education.gov.uk'    
  #ResourceGroupName: 's126d01-matching'
  WorkerASPSize: '1'
  WorkerASPInstances: '1'
  SQLDatabaseSkuName: 'S0'
  SQLDatabaseTier: 'Standard'
  BankHolidayGeneratorTrigger: '0 45 9  * * WED'
  EmployerFeedbackTrigger: '0 0 9 * * MON-FRI'
  ProviderFeedbackTrigger: '0 0 9 * * MON-FRI'
  ProviderReferenceTrigger: '0 0 7 * * *'

  applicationName: matching
  # SharedEnvResourceGroupName: 's126d01-matching-shared'
  # SharedSQLServerName: 's126d01-matching-shared-001-sqlsvr'
  testSqlDatabaseSkuName: 'S0'
  testSqlDatabaseTier: 'Standard'
  #ConfigStorageAccountName: 's126d01matchingconfigstr'
        
stages:
  - template: ./yaml/stages/matching-master-stage.yml

