jobs:
- job: DeploySharedInfrastructure
  pool:
    name: 'Azure Pipelines'
    vmImage: 'windows-2019'
  steps:
  - checkout: self

  - template: ./Infrastructure/steps/deploy-template.yml@devopsTemplates
    parameters:
      serviceConnection: $(serviceConnection)
      subscriptionId: $(subscriptionId)
      resourceGroupName: $(SharedEnvResourceGroupName)
      location: 'West Europe'
      templateFilePath: './azure/matching-shared.json'
      armParameterOverrideString: '-environmentNameAbbreviation "d01-matching" 
        -sqlServerAdminUsername "$(SQLServerAdminUsername)" 
        -sqlServerAdminPassword "$(SQLServerAdminPassword)" 
        -sqlServerActiveDirectoryAdminLogin "$(SQLServerActiveDirectoryAdminLogin)" 
        -sqlServerActiveDirectoryAdminObjectId "$(SQLServerActiveDirectoryAdminObjectId)" 
        -threatDetectionEmailAddress "$(ThreatDetectionEmailAddress)" 
        -azureWebsitesRPObjectId "$(AzureWebsitesRPObjectId)" 
        -keyVaultReadWriteObjectIds $(KeyVaultReadWriteObjectIds)'
      processOutputs: true