parameters:
- name: environmentNameAbbreviation
  type: string
jobs:
- job: DeployMatchingInfrastructure
  dependsOn: 
    - DeploySharedInfrastructure
  variables:
    SharedASPName: $[ dependencies.DeploySharedInfrastructure.outputs['armOutputs.armOutput.sharedASPName'] ]
    SharedKeyVaultName: $[ dependencies.DeploySharedInfrastructure.outputs['armOutputs.armOutput.sharedKeyVaultName'] ] 
    SharedSQLServerName: $[ dependencies.DeploySharedInfrastructure.outputs['armOutputs.armOutput.sharedSQLServerName'] ] 
    ConfigurationStorageConnectionString: $[ dependencies.DeploySharedInfrastructure.outputs['armOutputs.armOutput.configStorageConnectionString'] ]
    
  steps:
  - checkout: self

  - template: ./Infrastructure/steps/deploy-template.yml@devopsTemplates
    parameters:
      serviceConnection: $(serviceConnection)
      subscriptionId: $(subscriptionId)
      resourceGroupName: $(ResourceGroupName)
      location: 'West Europe'
      templateFilePath: './azure/matching-environmant.json'
      armParameterOverrideString: '-environmentNameAbbreviation "${{parameters.environmentNameAbbreviation}}"         
        -workerASPSize "$(WorkerASPSize)" 
        -workerASPInstances "$(WorkerASPInstances)" 
        -sharedASPName "$(SharedASPName)" 
        -sharedEnvResourceGroup "$(SharedEnvResourceGroupName)" 
        -sharedKeyVaultName "$(SharedKeyVaultName)" 
        -sharedSQLServerName "$(SharedSQLServerName)" 
        -sqlDatabaseSkuName "$(SQLDatabaseSkuName)" 
        -sqlDatabaseTier "$(SQLDatabaseTier)" 
        -configurationStorageConnectionString "$(ConfigurationStorageConnectionString)" 
        -uiCustomHostName "$(UICustomHostName)" 
        -certificateName "$(CertificateName)" 
        -bankHolidayGeneratorTrigger "$(BankHolidayGeneratorTrigger)" 
        -employerFeedbackTrigger "$(EmployerFeedbackTrigger)" 
        -providerFeedbackTrigger "$(ProviderFeedbackTrigger)" 
        -providerReferenceTrigger "$(ProviderReferenceTrigger)"'
      processOutputs: true