parameters:
  - name: serviceConnection
    type: string
  - name: sharedEnvironmentId
    type: string
jobs:
- job: PublishSite
  variables:
    ConfigStorageAccountName: $[ stageDependencies.DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}.DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}.outputs['DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}.armOutputs.armOutput.ConfigStorageAccountName'] ]
    uiAppName: $[ dependencies.DeployMatchingInfrastructure.outputs['armOutputs.armOutput.uiAppName'] ]
  pool:
    name: 'Azure Pipelines'
    vmImage: 'windows-2019'
  dependsOn: 
    - DeployMatchingInfrastructure 
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'appdrop'
      downloadPath: '$(System.ArtifactsDirectory)'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: ${{ parameters.serviceConnection}}
      appType: 'webApp'
      appName: '$(uiAppName)'
      deployToSlotOrASE: true
      resourceGroupName: '$(ResourceGroupName)'
      slotName: 'staging'
      package: '$(System.ArtifactsDirectory)/appdrop/Sfa.Tl.Matching.Web.zip'
      deploymentMethod: 'auto'
