parameters:
- name: SharedASPName
  type: string
- name: SharedEnvResourceGroupName
  type: string
- name: SharedKeyVaultName
  type: string
- name: SharedSQLServerName
  type: string
- name: ConfigurationStorageConnectionString
  type: string
- name: UICustomHostName
  type: string
- name: CertificateName
  type: string
- name: ResourceGroupName
  type: string


jobs:
  - job: DeployMatchingInfrastructure
    steps:
    - task: AzureResourceGroupDeployment@2
      displayName: 'Azure Deployment:Create Or Update Resource Group action on $(ResourceGroupName)'
      inputs:
        azureSubscription: '$(serviceConnection)'
        resourceGroupName: '$(ResourceGroupName)'
        location: 'West Europe'
        csmFile: './azure/matching-environmant.json'
        overrideParameters: '-environmentNameAbbreviation "d01-matching" 
          -workerASPSize "$(WorkerASPSize)" 
          -workerASPInstances "$(WorkerASPInstances)" 
          -sharedASPName "$(SharedASPName)" 
          -sharedEnvResourceGroup "$(SharedEnvResourceGroupName)" 
          -sharedKeyVaultName "$(SharedKeyVaultName)" 
          -sharedSQLServerName "$(SharedSQLServerName)" 
          -sqlDatabaseSkuName "$(SQLDatabaseSkuName)" 
          -sqlDatabaseTier "$(SQLDatabaseTier)" 
          -configurationStorageConnectionString "$(ConfigurationStorageConnectionString)" 
          -uiCustomHostName "$(UICustomHostName)" 
          -certificateName "$(CertificateName)" 
          -bankHolidayGeneratorTrigger "$(BankHolidayGeneratorTrigger)" 
          -employerFeedbackTrigger "$(EmployerFeedbackTrigger)" 
          -providerFeedbackTrigger "$(ProviderFeedbackTrigger)" 
          -providerReferenceTrigger "$(ProviderReferenceTrigger)"'
        deploymentOutputs: armOutputs