parameters:
- name: SharedEnvResourceGroupName
  type: string
- name: UICustomHostName
  type: string
- name: CertificateName
  type: string
- name: ResourceGroupName
  type: string
- name: SharedInfrastructureDependency
  type: string
jobs:
- job: DeployMatchingInfrastructure
  dependsOn: 
    - DeploySharedInfrastructure
  variables:
    SharedASPName: $[ dependencies.DeploySharedInfrastructure.outputs['armOutput.sharedASPName'] ]
    SharedKeyVaultName: $[ dependencies.DeploySharedInfrastructure.outputs['armOutput.sharedKeyVaultName'] ] 
    SharedSQLServerName: $[ dependencies.DeploySharedInfrastructure.outputs['armOutput.sharedSQLServerName'] ] 
    ConfigurationStorageConnectionString: $[ dependencies.DeploySharedInfrastructure.outputs['armOutput.configStorageConnectionString'] ]
    # SharedASPName: s126d01-matching-shared-asp
    # SharedKeyVaultName:  s126d01matchingsharedkv
    # SharedSQLServerName:  s126d01-matching-shared-sql
    # ConfigurationStorageConnectionString: configStorageConnectionString=DefaultEndpointsProtocol=https;AccountName=s126d01matchingconfigstr;AccountKey=s8UOhuwQ9Y/U3K7wMt6I4+PKW+zyjlIs7rDarxfncF9V3g3Ep/c89MlJrOyPjEqi4+Vzsu1o78nHX8gU0IKLmQ==;EndpointSuffix=core.windows.net 
    
  steps:
  - checkout: self
  - pwsh: |
      Write-Host $SharedSQLServerName
      
  - pwsh: Get-ChildItem -Recurse

  - template: ./Infrastructure/steps/deploy-template.yml@devopsTemplates
    parameters:
      serviceConnection: $(serviceConnection)
      subscriptionId: $(subscriptionId)
      resourceGroupName: $(ResourceGroupName)
      location: 'West Europe'
      templateFilePath: './azure/matching-environmant.json'
      armParameterOverrideString: '-environmentNameAbbreviation "s126d01-matching"         
        -workerASPSize "$(WorkerASPSize)" 
        -workerASPInstances "$(WorkerASPInstances)" 
        -sharedASPName "$(SharedASPName)" 
        -sharedEnvResourceGroup "$(SharedEnvResourceGroupName)" 
        -sharedKeyVaultName "$(SharedKeyVaultName)" 
        -sharedSQLServerName "$(SharedSQLServerName)" 
        -sqlDatabaseSkuName "$(SQLDatabaseSkuName)" 
        -sqlDatabaseTier "$(SQLDatabaseTier)" 
        -configurationStorageConnectionString "$(ConfigurationStorageConnectionString)" 
        -uiCustomHostName "$(UICustomHostName)" 
        -certificateName "$(CertificateName)" 
        -bankHolidayGeneratorTrigger "$(BankHolidayGeneratorTrigger)" 
        -employerFeedbackTrigger "$(EmployerFeedbackTrigger)" 
        -providerFeedbackTrigger "$(ProviderFeedbackTrigger)" 
        -providerReferenceTrigger "$(ProviderReferenceTrigger)"'
      processOutputs: true