parameters:
  - name: serviceConnection
    type: string
  - name: sharedEnvironmentId
    type: string
jobs:
- job: DeploySQLDatabase
  pool:
    name: 'Azure Pipelines'
    vmImage: 'windows-2019'
  dependsOn:
    - DeployMatchingInfrastructure 

  variables:
    SharedSQLServerName: $[ stageDependencies.DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}.DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}.outputs['DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}.armOutputs.armOutput.sharedSQLServerName'] ]
    DatabaseName: $[ dependencies.DeployMatchingInfrastructure.outputs['armOutputs.armOutput.sqlDatabaseName'] ]
  steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'sqldrop'
        downloadPath: '$(System.ArtifactsDirectory)'
   
    - task: SqlAzureDacpacDeployment@1
      displayName: 'Azure SQL Publish'
      inputs:
        azureSubscription: ${{ parameters.serviceConnection }}
        ServerName: '$(SharedSQLServerName).database.windows.net'
        DatabaseName: '$(DatabaseName)'
        SqlUsername: '$(SQLServerAdminUsername)'
        SqlPassword: '$(SQLServerAdminPassword)'
        DacpacFile: '$(System.ArtifactsDirectory)/sqldrop/src/Sfa.Tl.Matching.Database/bin/Release/Sfa.Tl.Matching.Database.dacpac'
        AdditionalArguments: '/p:GenerateSmartDefaults=True'

    - pwsh: | 
        $SqlConnectionString = az sql db show-connection-string -s $(SharedSQLServerName) -n $(DatabaseName) -c ado.net
        $SqlConnectionString = $SqlConnectionString -replace "<username>", '$(SQLServerAdminUsername)'
        $SqlConnectionString = $SqlConnectionString -replace "<password>", '$(SQLServerAdminPassword)'
        Write-Host "##vso[task.setvariable variable=SqlConnectionString;isOutput=true]$(SqlConnectionString)"
        
      name: SqlVariables

