parameters:
- name: serviceConnection
  type: string
- name: SharedEnvResourceGroupName
  type: string
- name: rgLocation
  type: string
- name: SQLServerAdminUsername
  type: string
- name: SQLServerAdminPassword
  type: string

jobs:
- job: DeploySharedInfrastructure
  pool:
    name: 'Azure Pipelines'
    vmImage: 'windows-2019'
  steps:
  - task: AzureResourceGroupDeployment@2
    displayName: 'Azure Deployment:Create Or Update Resource Group action on $(SharedEnvResourceGroupName)'
    inputs:
      azureSubscription: '$(serviceConnection)'
      resourceGroupName: '$(SharedEnvResourceGroupName)'
      location: 'West Europe'
      csmFile: './azure/matching-shared.json'
      overrideParameters: '-environmentNameAbbreviation "d01-matching" 
        -sqlServerAdminUsername "$(SQLServerAdminUsername)" 
        -sqlServerAdminPassword "$(SQLServerAdminPassword)" 
        -sqlServerActiveDirectoryAdminLogin "$(SQLServerActiveDirectoryAdminLogin)" 
        -sqlServerActiveDirectoryAdminObjectId "$(SQLServerActiveDirectoryAdminObjectId)" 
        -threatDetectionEmailAddress "$(ThreatDetectionEmailAddress)" 
        -azureWebsitesRPObjectId "$(AzureWebsitesRPObjectId)" 
        -keyVaultReadWriteObjectIds $(KeyVaultReadWriteObjectIds)'
      deploymentOutputs: sharedOutputs        
  
  - task: ARMOutputParserExtension@1
    displayName: 'Convert ARM Template Outputs to Variables'
    inputs:
      armOutput: '$(sharedOutputs)'    
