
jobs:
- job: DeploySharedInfrastructure
  steps:
  - checkout: self

  - template: ./Infrastructure/steps/deploy-template.yml@devopsTemplates
    parameters:
      serviceConnection: $(serviceConnection)
      subscriptionId: $(subscriptionId)
      resourceGroupName: $(SharedResourceGroup)
      location: 'West Europe'
      templateFilePath: './azure/matching-shared.json'
      armParameterOverrideString: '-environmentNameAbbreviation "d01-matching" 
        -sqlServerAdminUsername "$(SQLServerAdminUsername)" 
        -sqlServerAdminPassword "$(SQLServerAdminPassword)" 
        -sqlServerActiveDirectoryAdminLogin "$(SQLServerActiveDirectoryAdminLogin)" 
        -sqlServerActiveDirectoryAdminObjectId "$(SQLServerActiveDirectoryAdminObjectId)" 
        -threatDetectionEmailAddress "$(ThreatDetectionEmailAddress)" 
        -appServicePlanTier "$(AppServicePlanTier)" 
        -appServicePlanSize "$(AppServicePlanSize)" 
        -appServicePlanInstances "$(AppServicePlanInstances)" 
        -azureWebsitesRPObjectId "$(AzureWebsitesRPObjectId)" 
        -keyVaultReadWriteObjectIds "$(KeyVaultReadWriteObjectIds)"
        -keyVaultFullAccessObjectIds "$(keyVaultFullAccessObjectIds)"'
      processOutputs: true