IF OBJECT_ID('tempdb..#Roles') IS NOT NULL 
    DROP TABLE #Roles ;

create table #Roles
(
    Username varchar(50),
    Team varchar(20),
    Region varchar(30)
)

INSERT INto #Roles
VALUES
    ('Rebecca Mitchell',	'SME Outbound', ''),
    ('Christopher Hope',	'SME Outbound', ''),
    ('Sonia Begum',			'SME Outbound', ''),
    ('John Marshall',		'SME Outbound', ''),
    ('Callum Middleton',	'SME Outbound', ''),
    ('Jamie Dale',			'SME Outbound', ''),
    ('Nicole Myers',		'SME Outbound', ''),
    ('Cameron Mackay',		'SME Outbound', ''),
    ('Chris Michaels',		'SME Outbound', ''),
    ('Kieran Levison',		'SME Outbound', ''),
    ('Jasmine Falcus',		'SME Outbound', ''),
    ('Claire Yates',		'SME Outbound', ''),
    ('Kieran Sleep',		'SME Outbound', ''),
    ('Janette McKenna',		'SME Outbound', ''),
    ('Neha Gera',			'SME Outbound', ''),
    ('Gavin Humphreys',		'SME Outbound', ''),
    ('Thomas Watson',		'TAM', ''),
    ('Abbie Bland',			'TAM', ''),
    ('Mandy Wong',			'TAM', ''),
    ('Ali Falahi',			'TAM', ''),
    ('Waheeda Rehman',		'TAM', ''),
    ('Elizabeth Sampson',	'TAM', ''),
    ('Jack Routledge',		'TAM', ''),
    ('Lee Potter',			'TAM', ''),
    ('Michael Mander ',		'TAM', ''),
    ('Michael O''Hare',		'TAM', ''),
    ('Horatio Lupea',		'TAM', ''),
    ('Eliud Luciani',		'TAM', ''),
    ('Dan Humble',			'TAM', ''),
    ('Czelsie Weston',		'TAM', ''),
    ('Lorna Todd',			'TAM', ''),
    ('Mark McCreesh',		'TAM', ''),
    ('Laura Roberts',		'TAM', ''),
    ('Scott Brookfield',	'TAM', ''),
    ('Blaine Harrison',		'TAM', ''),
    ('Andrew Lunn',			'NAM', 'LSE NAM'),
    ('Ben Derham',			'NAM', 'LSE NAM'),
    ('Joseph Finlay',		'NAM', 'LSE NAM'),
    ('Lara Allen',			'NAM', 'LSE NAM'),
    ('Monique Lavers',		'NAM', 'LSE NAM'),
    ('Poonam Joshi',		'NAM', 'LSE NAM'),
    ('Simon Peek',			'NAM', 'LSE NAM'),
    ('Steve Latus',			'NAM', 'LSE NAM'),
    ('Subash Sachania',		'NAM', 'LSE NAM'),
    ('Sue Welsh',			'NAM', 'LSE NAM'),
    ('Sue Winrow',			'NAM', 'LSE NAM'),
    ('Ann Barnes',			'NAM', 'North NAM'),
    ('Anthony Knowles',		'NAM', 'North NAM'),
    ('Claire Murray',		'NAM', 'North NAM'),
    ('Bethany Pawson',		'NAM', 'North NAM'),
    ('Marianne Burrows',	'NAM', 'North NAM'),
    ('Mike Long',			'NAM', 'North NAM'),
    ('Nicky Martin',		'NAM', 'North NAM'),
    ('Paula Merifield',		'NAM', 'North NAM'),
    ('Steven Thompson',		'NAM', 'North NAM'),
    ('Beena Nana',			'NAM', 'Central NAM'),
    ('Jennifer Weir',		'NAM', 'Central NAM'),
    ('John Myers',			'NAM', 'Central NAM'),
    ('Julia Bakewell',		'NAM', 'Central NAM'),
    ('Kyla Mulvaney',		'NAM', 'Central NAM'),
    ('Mark Coulson',		'NAM', 'Central NAM'),
    ('Rekha Patel',			'NAM', 'Central NAM'),
    ('Toni Moore',			'NAM', 'Central NAM'),
    ('Victoria Hipkiss',	'NAM', 'Central NAM'),
    ('Bertie Hutchins',		'NAM', 'SSW NAM'),
    ('Bruce Hollobone',		'NAM', 'SSW NAM'),
    ('Claire Edmondson',	'NAM', 'SSW NAM'),
    ('Mark Howard',			'NAM', 'SSW NAM'),
    ('Nicola Akers',		'NAM', 'SSW NAM'),
    ('Richard Daulton',		'NAM', 'SSW NAM'),
    ('Scott Hatwood',		'NAM', 'SSW NAM'),
    ('Steven Nicolson',		'NAM', 'SSW NAM'),
    ('Elaine McCully',		'NAM', 'Needs reallocation'),
    ('Ian Ryan',			'NAM', 'Needs reallocation'),
    ('Lauren Hutchinson',	'NAM', ''),
    ('Nazrul Haque',		'EST', ''),
    ('Amy Woolrych',		'EST', ''),
    ('Robert Bruce',		'EST', ''),
    ('Jessica Hawkins',		'EST', ''),
    ('Anna Darling',		'EST', ''),
    ('Natalie Richardson',	'EST', ''),
    ('Keara Kerr',			'EST', ''),
    ('Julia Hunter',		'EST', ''),
    ('Rashi Singh',			'EST', ''),
    ('Laura Winter',		'EST', ''),
    ('Amanda Blair',		'EST', ''),
    ('Meg Huddleston',		'EST', ''),
    ('Leah Wiseman',		'EST', ''),
    ('Stephen Short',		'EST', ''),
    ('Jillian Gordon',		'EST', ''),
    ('(John) Tony Imerson', 'EST', ''),
    ('Shannelle Marshall',	'EST', ''),
    ('Victoria Ord',		'EST', ''),
    ('Melissa Harrison',	'EST', ''),
    ('Jonathan Dunn',		'EST', ''),
    ('Angela Wood-Smith',	'EST', ''),
    ('Lindsey Smith',		'EST', ''),
    ('Suzy Smith',			'EST', ''),
    ('Hayley Turner',		'EST', ''),
    ('Yasmine Moussa',		'EST', ''),
    ('Emma Turnbull',		'EST', ''),
    ('Jack Mohan',			'EST', ''),
    ('Richard Straker',		'EST', ''),
    ('Elle Smart',			'EST', ''),
    ('Anna Newell',			'EST', ''),
    ('Caitlin Forrest',		'EST', ''),
    ('Chelsea Bryant',		'EST', ''),
    ('Oliver Gaunt',		'EST', ''),
    ('Stephanie Fellows',	'EST', ''),
    ('Nicola Harris',		'EST', ''),
    ('Elizabeth Sanders',	'EST', ''),
    ('Gemma Barella',		'EST', ''),
    ('Emma Craig',			'EST', ''),
    ('Carl Duncan',			'EST', ''),
    ('Kevin Bulman',		'EST', ''),
    ('Caitlin McKenna',		'EST', ''),
    ('Julieann Stronach',	'EST', ''),
	('3 Tmatching',			'NAM', 'SSW NAM'),
    ('2 Tmatching',			'TAM', ''),
    ('1 Tmatching',			'SME Outbound', '')

;WITH CTE AS (
    SELECT
        oi.id AS OpportunityItemId,
        count(p.Id) AS ProviderCount
    from [Provider] AS P
        INNER JOIN ProviderVenue AS pv ON pv.ProviderId = p.Id
        INNER JOIN Referral AS rf ON rf.ProviderVenueId = pv.id
        INNER JOIN OpportunityItem AS oi ON rf.OpportunityItemId = oi.id
    GROUP BY oi.id
)
SELECT
    oi.id AS OpportunityItemId,
    oi.OpportunityType,
    oi.IsCompleted,
    oi.IsSaved,
    CAST(CASE WHEN oi.IsSaved = 1 and oi.IsCompleted = 0 THEN 1 ELSE 0 END AS BIT) AS PipelineOpportunity,
    o.EmployerId,
    e.CompanyName,
    e.Aupa,
    e.Owner,
    oi.Postcode AS EmployerPostCodeEnteredInSearch,
    oi.PlacementsKnown,
    oi.Placements,
    oi.JobRole,
    cte.ProviderCount,
    rt.[Name] as RouteName,
    rl.Region,
    rl.Team,
    oi.CreatedBy AS Username,
    DATEADD(DAY, 6 - DATEPART(WEEKDAY, o.CreatedOn), CAST(o.CreatedOn AS  DATE)) WeekEndDate,
    LEFT(DATENAME(MONTH, o.CreatedOn),3) + ' ' + RIGHT('00' + CAST(YEAR(o.CreatedOn) AS VARCHAR),2) as [Date]
FROM Opportunity as o
    INNER JOIN OpportunityItem as oi on o.Id = oi.OpportunityId
    INNER JOIN [Route] as rt on rt.Id = oi.RouteId
    LEFT JOIN CTE ON cte.OpportunityItemId = oi.Id
    LEFT JOIN #Roles as rl on o.CreatedBy = rl.Username
    LEFT JOIN Employer as e on  e.Id = o.EmployerId
WHERE 
    oi.IsSaved = 1
ORDER BY 
    OpportunityType DESC,
 	IsCompleted DESC,
 	IsSaved DESC,
	OpportunityItemId