CREATE TABLE [dbo].[Employer]
(
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Account] [uniqueidentifier] NOT NULL,
	[CompanyName] NVARCHAR(160) NOT NULL, 
	[AlsoKnownAs] NVARCHAR(100) NULL, 
	[AupaStatus] INT NOT NULL,
	[CompanyType] INT NOT NULL, 
	[Phone] VARCHAR(150) NULL,
	[Email] VARCHAR(320) NULL,
	[Website] NVARCHAR(200) NULL,
	[AddressName] NVARCHAR(200) NULL,
	[Address1] VARCHAR(200) NOT NULL,
	[Address2] VARCHAR(200) NULL,
	[Address3] VARCHAR(200) NULL,
	[City] VARCHAR(100) NOT NULL,
	[County] VARCHAR(100) NULL,
	[PostCode] VARCHAR(10) NOT NULL,
	[CreatedBy] NVARCHAR(150) NOT NULL,
	[CreatedOn] DATETIME2 NOT NULL DEFAULT GETDATE(), 
	[ModifiedBy] NVARCHAR(150) NOT NULL,
	[ModifiedOn] DATETIME2 NOT NULL,
	[Owner] NVARCHAR(150) NOT NULL,
)