CREATE TABLE [dbo].[Provider]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(50) NOT NULL,
	[UKPRN] NVARCHAR(50) NOT NULL,
    [CreatedOn] DATETIME2 NOT NULL DEFAULT GetDate(), 
    [ModifiedOn] DATETIME2 NULL,
)
