//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.ServiceModel;
using System.ServiceModel.Channels;
using System.ServiceModel.Description;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Schema;
using System.Xml.Serialization;

namespace Sfa.Tl.Matching.Api.Clients.Connected_Services.Sfa.Tl.Matching.UkRlp.Api.Client
{
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [DebuggerStepThrough()]
    [XmlType(AnonymousType=true, Namespace="http://ukrlp.co.uk.server.ws.v3")]
    public partial class faultDetail
    {
        
        private string majorField;
        
        private string minorField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public string major
        {
            get
            {
                return this.majorField;
            }
            set
            {
                this.majorField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
        public string minor
        {
            get
            {
                return this.minorField;
            }
            set
            {
                this.minorField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://www.govtalk.gov.uk/people/PersonDescriptives")]
    public partial class PersonMaritalStatusStructure
    {
        
        private MaritalStatusType maritalStatusField;
        
        private VerificationLevelType verificationLevelField;
        
        private bool verificationLevelFieldSpecified;
        
        /// <remarks/>
        [XmlElement(Order=0)]
        public MaritalStatusType MaritalStatus
        {
            get
            {
                return this.maritalStatusField;
            }
            set
            {
                this.maritalStatusField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=1)]
        public VerificationLevelType VerificationLevel
        {
            get
            {
                return this.verificationLevelField;
            }
            set
            {
                this.verificationLevelField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool VerificationLevelSpecified
        {
            get
            {
                return this.verificationLevelFieldSpecified;
            }
            set
            {
                this.verificationLevelFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [XmlType(Namespace="http://www.govtalk.gov.uk/core")]
    public enum MaritalStatusType
    {
        
        /// <remarks/>
        s,
        
        /// <remarks/>
        m,
        
        /// <remarks/>
        d,
        
        /// <remarks/>
        w,
        
        /// <remarks/>
        n,
        
        /// <remarks/>
        p,
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [XmlType(Namespace="http://www.govtalk.gov.uk/people/PersonDescriptives")]
    public enum VerificationLevelType
    {
        
        /// <remarks/>
        [XmlEnum("Level 0")]
        Level0,
        
        /// <remarks/>
        [XmlEnum("Level 1")]
        Level1,
        
        /// <remarks/>
        [XmlEnum("Level 2")]
        Level2,
        
        /// <remarks/>
        [XmlEnum("Level 3")]
        Level3,
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://www.govtalk.gov.uk/people/PersonDescriptives")]
    public partial class PersonDeathDateStructure
    {
        
        private DateTime personDeathDateField;
        
        private VerificationLevelType verificationLevelField;
        
        private bool verificationLevelFieldSpecified;
        
        /// <remarks/>
        [XmlElement(DataType="date", Order=0)]
        public DateTime PersonDeathDate
        {
            get
            {
                return this.personDeathDateField;
            }
            set
            {
                this.personDeathDateField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=1)]
        public VerificationLevelType VerificationLevel
        {
            get
            {
                return this.verificationLevelField;
            }
            set
            {
                this.verificationLevelField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool VerificationLevelSpecified
        {
            get
            {
                return this.verificationLevelFieldSpecified;
            }
            set
            {
                this.verificationLevelFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://www.govtalk.gov.uk/people/PersonDescriptives")]
    public partial class PersonBirthDateStructure
    {
        
        private DateTime personBirthDateField;
        
        private VerificationLevelType verificationLevelField;
        
        private bool verificationLevelFieldSpecified;
        
        /// <remarks/>
        [XmlElement(DataType="date", Order=0)]
        public DateTime PersonBirthDate
        {
            get
            {
                return this.personBirthDateField;
            }
            set
            {
                this.personBirthDateField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=1)]
        public VerificationLevelType VerificationLevel
        {
            get
            {
                return this.verificationLevelField;
            }
            set
            {
                this.verificationLevelField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool VerificationLevelSpecified
        {
            get
            {
                return this.verificationLevelFieldSpecified;
            }
            set
            {
                this.verificationLevelFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public partial class AONrangeStructure
    {
        
        private string numberField;
        
        private string suffixField;
        
        /// <remarks/>
        [XmlElement(DataType="positiveInteger", Order=0)]
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=1)]
        public string Suffix
        {
            get
            {
                return this.suffixField;
            }
            set
            {
                this.suffixField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public partial class LandAndPropertyIdentifierStructure
    {
        
        private AONstructure pAONField;
        
        private AONstructure sAONField;
        
        private string postTownField;
        
        private string postCodeField;
        
        private string levelField;
        
        private LogicalStatusType logicalStatusField;
        
        private bool officialAddressMarkerField;
        
        private bool officialAddressMarkerFieldSpecified;
        
        private DateTime lPIstartDateField;
        
        private DateTime lPIentryDateField;
        
        private DateTime lPIendDateField;
        
        private bool lPIendDateFieldSpecified;
        
        private DateTime lPIlastUpdateDateField;
        
        private object itemField;
        
        /// <remarks/>
        [XmlElement(Order=0)]
        public AONstructure PAON
        {
            get
            {
                return this.pAONField;
            }
            set
            {
                this.pAONField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=1)]
        public AONstructure SAON
        {
            get
            {
                return this.sAONField;
            }
            set
            {
                this.sAONField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=2)]
        public string PostTown
        {
            get
            {
                return this.postTownField;
            }
            set
            {
                this.postTownField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=3)]
        public string PostCode
        {
            get
            {
                return this.postCodeField;
            }
            set
            {
                this.postCodeField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=4)]
        public string Level
        {
            get
            {
                return this.levelField;
            }
            set
            {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=5)]
        public LogicalStatusType LogicalStatus
        {
            get
            {
                return this.logicalStatusField;
            }
            set
            {
                this.logicalStatusField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=6)]
        public bool OfficialAddressMarker
        {
            get
            {
                return this.officialAddressMarkerField;
            }
            set
            {
                this.officialAddressMarkerField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool OfficialAddressMarkerSpecified
        {
            get
            {
                return this.officialAddressMarkerFieldSpecified;
            }
            set
            {
                this.officialAddressMarkerFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="date", Order=7)]
        public DateTime LPIstartDate
        {
            get
            {
                return this.lPIstartDateField;
            }
            set
            {
                this.lPIstartDateField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="date", Order=8)]
        public DateTime LPIentryDate
        {
            get
            {
                return this.lPIentryDateField;
            }
            set
            {
                this.lPIentryDateField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="date", Order=9)]
        public DateTime LPIendDate
        {
            get
            {
                return this.lPIendDateField;
            }
            set
            {
                this.lPIendDateField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool LPIendDateSpecified
        {
            get
            {
                return this.lPIendDateFieldSpecified;
            }
            set
            {
                this.lPIendDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="date", Order=10)]
        public DateTime LPIlastUpdateDate
        {
            get
            {
                return this.lPIlastUpdateDateField;
            }
            set
            {
                this.lPIlastUpdateDateField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("Street", typeof(StreetStructure), Order=11)]
        [XmlElement("USRN", typeof(string), DataType="integer", Order=11)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public partial class AONstructure
    {
        
        private string descriptionField;
        
        /// <remarks/>
        [XmlElement(Order=0)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [XmlType(Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public enum LogicalStatusType
    {
        
        /// <remarks/>
        [XmlEnum("1")]
        Item1,
        
        /// <remarks/>
        [XmlEnum("2")]
        Item2,
        
        /// <remarks/>
        [XmlEnum("3")]
        Item3,
        
        /// <remarks/>
        [XmlEnum("5")]
        Item5,
        
        /// <remarks/>
        [XmlEnum("6")]
        Item6,
        
        /// <remarks/>
        [XmlEnum("8")]
        Item8,
        
        /// <remarks/>
        [XmlEnum("9")]
        Item9,
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public partial class StreetStructure
    {
        
        private StreetReferenceTypeType streetReferenceTypeField;
        
        private CoordinateStructure startCoordinateField;
        
        private CoordinateStructure endCoordinateField;
        
        private decimal toleranceField;
        
        private string streetVersionNumberField;
        
        private DateTime streetEntryDateField;
        
        private DateTime streetClosureDateField;
        
        private bool streetClosureDateFieldSpecified;
        
        private string responsibleAuthorityField;
        
        private StreetDescriptiveIdentifierStructure descriptiveIdentifierField;
        
        private StreetDescriptiveIdentifierStructure streetAliasField;
        
        private StreetStructureStreetCrossReferences streetCrossReferencesField;
        
        private string usrnField;
        
        /// <remarks/>
        [XmlElement(Order=0)]
        public StreetReferenceTypeType StreetReferenceType
        {
            get
            {
                return this.streetReferenceTypeField;
            }
            set
            {
                this.streetReferenceTypeField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=1)]
        public CoordinateStructure StartCoordinate
        {
            get
            {
                return this.startCoordinateField;
            }
            set
            {
                this.startCoordinateField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=2)]
        public CoordinateStructure EndCoordinate
        {
            get
            {
                return this.endCoordinateField;
            }
            set
            {
                this.endCoordinateField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=3)]
        public decimal Tolerance
        {
            get
            {
                return this.toleranceField;
            }
            set
            {
                this.toleranceField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="positiveInteger", Order=4)]
        public string StreetVersionNumber
        {
            get
            {
                return this.streetVersionNumberField;
            }
            set
            {
                this.streetVersionNumberField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="date", Order=5)]
        public DateTime StreetEntryDate
        {
            get
            {
                return this.streetEntryDateField;
            }
            set
            {
                this.streetEntryDateField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="date", Order=6)]
        public DateTime StreetClosureDate
        {
            get
            {
                return this.streetClosureDateField;
            }
            set
            {
                this.streetClosureDateField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool StreetClosureDateSpecified
        {
            get
            {
                return this.streetClosureDateFieldSpecified;
            }
            set
            {
                this.streetClosureDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="integer", Order=7)]
        public string ResponsibleAuthority
        {
            get
            {
                return this.responsibleAuthorityField;
            }
            set
            {
                this.responsibleAuthorityField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=8)]
        public StreetDescriptiveIdentifierStructure DescriptiveIdentifier
        {
            get
            {
                return this.descriptiveIdentifierField;
            }
            set
            {
                this.descriptiveIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=9)]
        public StreetDescriptiveIdentifierStructure StreetAlias
        {
            get
            {
                return this.streetAliasField;
            }
            set
            {
                this.streetAliasField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=10)]
        public StreetStructureStreetCrossReferences StreetCrossReferences
        {
            get
            {
                return this.streetCrossReferencesField;
            }
            set
            {
                this.streetCrossReferencesField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute(DataType="integer")]
        public string usrn
        {
            get
            {
                return this.usrnField;
            }
            set
            {
                this.usrnField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [XmlType(Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public enum StreetReferenceTypeType
    {
        
        /// <remarks/>
        [XmlEnum("1")]
        Item1,
        
        /// <remarks/>
        [XmlEnum("2")]
        Item2,
        
        /// <remarks/>
        [XmlEnum("3")]
        Item3,
        
        /// <remarks/>
        [XmlEnum("4")]
        Item4,
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public partial class CoordinateStructure
    {
        
        private ulong xField;
        
        private ulong yField;
        
        /// <remarks/>
        [XmlElement(Order=0)]
        public ulong X
        {
            get
            {
                return this.xField;
            }
            set
            {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=1)]
        public ulong Y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public partial class StreetDescriptiveIdentifierStructure
    {
        
        private string streetDescriptionField;
        
        private string localityField;
        
        private string[] itemsField;
        
        private ItemsChoiceType1[] itemsElementNameField;
        
        /// <remarks/>
        [XmlElement(Order=0)]
        public string StreetDescription
        {
            get
            {
                return this.streetDescriptionField;
            }
            set
            {
                this.streetDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=1)]
        public string Locality
        {
            get
            {
                return this.localityField;
            }
            set
            {
                this.localityField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("AdministrativeArea", typeof(string), Order=2)]
        [XmlElement("Town", typeof(string), Order=2)]
        [XmlChoiceIdentifier("ItemsElementName")]
        public string[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("ItemsElementName", Order=3)]
        [XmlIgnore()]
        public ItemsChoiceType1[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [XmlType(Namespace="http://www.govtalk.gov.uk/people/bs7666", IncludeInSchema=false)]
    public enum ItemsChoiceType1
    {
        
        /// <remarks/>
        AdministrativeArea,
        
        /// <remarks/>
        Town,
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [DebuggerStepThrough()]
    [XmlType(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public partial class StreetStructureStreetCrossReferences
    {
        
        private object[] itemsField;
        
        /// <remarks/>
        [XmlElement("ElementaryStreetUnit", typeof(ElementaryStreetUnitStructure), Order=0)]
        [XmlElement("UniqueStreetReferenceNumbers", typeof(string), DataType="integer", Order=0)]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public partial class ElementaryStreetUnitStructure
    {
        
        private string eSUidentityField;
        
        private string eSUversionField;
        
        private DateTime eSUentryDateField;
        
        private DateTime eSUclosureDateField;
        
        private bool eSUclosureDateFieldSpecified;
        
        private CoordinateStructure startCoordinateField;
        
        private CoordinateStructure endCoordinateField;
        
        private decimal toleranceField;
        
        private CoordinateStructure[] intermediateCoordField;
        
        /// <remarks/>
        [XmlElement(Order=0)]
        public string ESUidentity
        {
            get
            {
                return this.eSUidentityField;
            }
            set
            {
                this.eSUidentityField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="positiveInteger", Order=1)]
        public string ESUversion
        {
            get
            {
                return this.eSUversionField;
            }
            set
            {
                this.eSUversionField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="date", Order=2)]
        public DateTime ESUentryDate
        {
            get
            {
                return this.eSUentryDateField;
            }
            set
            {
                this.eSUentryDateField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="date", Order=3)]
        public DateTime ESUclosureDate
        {
            get
            {
                return this.eSUclosureDateField;
            }
            set
            {
                this.eSUclosureDateField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool ESUclosureDateSpecified
        {
            get
            {
                return this.eSUclosureDateFieldSpecified;
            }
            set
            {
                this.eSUclosureDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=4)]
        public CoordinateStructure StartCoordinate
        {
            get
            {
                return this.startCoordinateField;
            }
            set
            {
                this.startCoordinateField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=5)]
        public CoordinateStructure EndCoordinate
        {
            get
            {
                return this.endCoordinateField;
            }
            set
            {
                this.endCoordinateField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=6)]
        public decimal Tolerance
        {
            get
            {
                return this.toleranceField;
            }
            set
            {
                this.toleranceField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("IntermediateCoord", Order=7)]
        public CoordinateStructure[] IntermediateCoord
        {
            get
            {
                return this.intermediateCoordField;
            }
            set
            {
                this.intermediateCoordField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public partial class BasicLandAndPropertyUnitStructure
    {
        
        private string uniquePropertyReferenceNumberField;
        
        private string custodianCodeField;
        
        private RepresentativePointCodeType representativePointCodeField;
        
        private LogicalStatusType logicalStatusField;
        
        private CoordinateStructure gridReferenceField;
        
        private DateTime bLPUentryDateField;
        
        private DateTime bLPUstartDateField;
        
        private DateTime bLPUendDateField;
        
        private bool bLPUendDateFieldSpecified;
        
        private DateTime bLPUlastUpdateDateField;
        
        private LandAndPropertyIdentifierStructure[] landAndPropertyIdentifierField;
        
        private ProvenanceStructure[] provenanceField;
        
        /// <remarks/>
        [XmlElement(DataType="integer", Order=0)]
        public string UniquePropertyReferenceNumber
        {
            get
            {
                return this.uniquePropertyReferenceNumberField;
            }
            set
            {
                this.uniquePropertyReferenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="integer", Order=1)]
        public string CustodianCode
        {
            get
            {
                return this.custodianCodeField;
            }
            set
            {
                this.custodianCodeField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=2)]
        public RepresentativePointCodeType RepresentativePointCode
        {
            get
            {
                return this.representativePointCodeField;
            }
            set
            {
                this.representativePointCodeField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=3)]
        public LogicalStatusType LogicalStatus
        {
            get
            {
                return this.logicalStatusField;
            }
            set
            {
                this.logicalStatusField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=4)]
        public CoordinateStructure GridReference
        {
            get
            {
                return this.gridReferenceField;
            }
            set
            {
                this.gridReferenceField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="date", Order=5)]
        public DateTime BLPUentryDate
        {
            get
            {
                return this.bLPUentryDateField;
            }
            set
            {
                this.bLPUentryDateField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="date", Order=6)]
        public DateTime BLPUstartDate
        {
            get
            {
                return this.bLPUstartDateField;
            }
            set
            {
                this.bLPUstartDateField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="date", Order=7)]
        public DateTime BLPUendDate
        {
            get
            {
                return this.bLPUendDateField;
            }
            set
            {
                this.bLPUendDateField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool BLPUendDateSpecified
        {
            get
            {
                return this.bLPUendDateFieldSpecified;
            }
            set
            {
                this.bLPUendDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="date", Order=8)]
        public DateTime BLPUlastUpdateDate
        {
            get
            {
                return this.bLPUlastUpdateDateField;
            }
            set
            {
                this.bLPUlastUpdateDateField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("LandAndPropertyIdentifier", Order=9)]
        public LandAndPropertyIdentifierStructure[] LandAndPropertyIdentifier
        {
            get
            {
                return this.landAndPropertyIdentifierField;
            }
            set
            {
                this.landAndPropertyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("Provenance", Order=10)]
        public ProvenanceStructure[] Provenance
        {
            get
            {
                return this.provenanceField;
            }
            set
            {
                this.provenanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [XmlType(Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public enum RepresentativePointCodeType
    {
        
        /// <remarks/>
        [XmlEnum("1")]
        Item1,
        
        /// <remarks/>
        [XmlEnum("2")]
        Item2,
        
        /// <remarks/>
        [XmlEnum("3")]
        Item3,
        
        /// <remarks/>
        [XmlEnum("4")]
        Item4,
        
        /// <remarks/>
        [XmlEnum("5")]
        Item5,
        
        /// <remarks/>
        [XmlEnum("9")]
        Item9,
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public partial class ProvenanceStructure
    {
        
        private ProvenanceCodeType provenanceCodeField;
        
        private string annotationField;
        
        private DateTime provEntryDateField;
        
        private DateTime provStartDateField;
        
        private DateTime provEndDateField;
        
        private bool provEndDateFieldSpecified;
        
        private DateTime provLastUpdateDateField;
        
        private BLPUextentStructure bLPUextentField;
        
        /// <remarks/>
        [XmlElement(Order=0)]
        public ProvenanceCodeType ProvenanceCode
        {
            get
            {
                return this.provenanceCodeField;
            }
            set
            {
                this.provenanceCodeField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=1)]
        public string Annotation
        {
            get
            {
                return this.annotationField;
            }
            set
            {
                this.annotationField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="date", Order=2)]
        public DateTime ProvEntryDate
        {
            get
            {
                return this.provEntryDateField;
            }
            set
            {
                this.provEntryDateField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="date", Order=3)]
        public DateTime ProvStartDate
        {
            get
            {
                return this.provStartDateField;
            }
            set
            {
                this.provStartDateField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="date", Order=4)]
        public DateTime ProvEndDate
        {
            get
            {
                return this.provEndDateField;
            }
            set
            {
                this.provEndDateField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool ProvEndDateSpecified
        {
            get
            {
                return this.provEndDateFieldSpecified;
            }
            set
            {
                this.provEndDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="date", Order=5)]
        public DateTime ProvLastUpdateDate
        {
            get
            {
                return this.provLastUpdateDateField;
            }
            set
            {
                this.provLastUpdateDateField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=6)]
        public BLPUextentStructure BLPUextent
        {
            get
            {
                return this.bLPUextentField;
            }
            set
            {
                this.bLPUextentField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [XmlType(Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public enum ProvenanceCodeType
    {
        
        /// <remarks/>
        T,
        
        /// <remarks/>
        L,
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        R,
        
        /// <remarks/>
        P,
        
        /// <remarks/>
        O,
        
        /// <remarks/>
        U,
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public partial class BLPUextentStructure
    {
        
        private string sourceDescriptionField;
        
        private DateTime extentEntryDateField;
        
        private DateTime extentSourceDateField;
        
        private DateTime extentStartDateField;
        
        private DateTime extentEndDateField;
        
        private bool extentEndDateFieldSpecified;
        
        private DateTime extentLastUpdateDateField;
        
        private BLPUpolygonStructure[] extentDefinitionField;
        
        /// <remarks/>
        [XmlElement(Order=0)]
        public string SourceDescription
        {
            get
            {
                return this.sourceDescriptionField;
            }
            set
            {
                this.sourceDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="date", Order=1)]
        public DateTime ExtentEntryDate
        {
            get
            {
                return this.extentEntryDateField;
            }
            set
            {
                this.extentEntryDateField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="date", Order=2)]
        public DateTime ExtentSourceDate
        {
            get
            {
                return this.extentSourceDateField;
            }
            set
            {
                this.extentSourceDateField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="date", Order=3)]
        public DateTime ExtentStartDate
        {
            get
            {
                return this.extentStartDateField;
            }
            set
            {
                this.extentStartDateField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="date", Order=4)]
        public DateTime ExtentEndDate
        {
            get
            {
                return this.extentEndDateField;
            }
            set
            {
                this.extentEndDateField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool ExtentEndDateSpecified
        {
            get
            {
                return this.extentEndDateFieldSpecified;
            }
            set
            {
                this.extentEndDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="date", Order=5)]
        public DateTime ExtentLastUpdateDate
        {
            get
            {
                return this.extentLastUpdateDateField;
            }
            set
            {
                this.extentLastUpdateDateField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("ExtentDefinition", Order=6)]
        public BLPUpolygonStructure[] ExtentDefinition
        {
            get
            {
                return this.extentDefinitionField;
            }
            set
            {
                this.extentDefinitionField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public partial class BLPUpolygonStructure
    {
        
        private string polygonIDField;
        
        private BLPUpolygonStructurePolygonType polygonTypeField;
        
        private bool polygonTypeFieldSpecified;
        
        private object[] itemsField;
        
        /// <remarks/>
        [XmlElement(DataType="positiveInteger", Order=0)]
        public string PolygonID
        {
            get
            {
                return this.polygonIDField;
            }
            set
            {
                this.polygonIDField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=1)]
        public BLPUpolygonStructurePolygonType PolygonType
        {
            get
            {
                return this.polygonTypeField;
            }
            set
            {
                this.polygonTypeField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool PolygonTypeSpecified
        {
            get
            {
                return this.polygonTypeFieldSpecified;
            }
            set
            {
                this.polygonTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("ExternalRef", typeof(ulong), Order=2)]
        [XmlElement("Vertices", typeof(CoordinateStructure), Order=2)]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [XmlType(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public enum BLPUpolygonStructurePolygonType
    {
        
        /// <remarks/>
        H,
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://ukrlp.co.uk.server.ws.v3")]
    public partial class ProviderQueryResultStructure
    {
        
        private ProviderRecordStructure[] matchingProviderRecordsField;
        
        private string queryIdField;
        
        private string stakeholderIdField;
        
        private string schemaVersionField;
        
        /// <remarks/>
        [XmlElement("MatchingProviderRecords", Form=XmlSchemaForm.Unqualified, Order=0)]
        public ProviderRecordStructure[] MatchingProviderRecords
        {
            get
            {
                return this.matchingProviderRecordsField;
            }
            set
            {
                this.matchingProviderRecordsField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, DataType="integer", Order=1)]
        public string QueryId
        {
            get
            {
                return this.queryIdField;
            }
            set
            {
                this.queryIdField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, DataType="integer", Order=2)]
        public string StakeholderId
        {
            get
            {
                return this.stakeholderIdField;
            }
            set
            {
                this.stakeholderIdField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string SchemaVersion
        {
            get
            {
                return this.schemaVersionField;
            }
            set
            {
                this.schemaVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://ukrlp.co.uk.server.ws.v3")]
    public partial class ProviderRecordStructure
    {
        
        private string unitedKingdomProviderReferenceNumberField;
        
        private string providerNameField;
        
        private string providerStatusField;
        
        private DateTime providerVerificationDateField;
        
        private bool providerVerificationDateFieldSpecified;
        
        private DateTime expiryDateField;
        
        private bool expiryDateFieldSpecified;
        
        private AssociationRecordStructure[] providerAssociationsField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, DataType="positiveInteger", Order=0)]
        public string UnitedKingdomProviderReferenceNumber
        {
            get
            {
                return this.unitedKingdomProviderReferenceNumberField;
            }
            set
            {
                this.unitedKingdomProviderReferenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
        public string ProviderName
        {
            get
            {
                return this.providerNameField;
            }
            set
            {
                this.providerNameField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=2)]
        public string ProviderStatus
        {
            get
            {
                return this.providerStatusField;
            }
            set
            {
                this.providerStatusField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=4)]
        public DateTime ProviderVerificationDate
        {
            get
            {
                return this.providerVerificationDateField;
            }
            set
            {
                this.providerVerificationDateField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool ProviderVerificationDateSpecified
        {
            get
            {
                return this.providerVerificationDateFieldSpecified;
            }
            set
            {
                this.providerVerificationDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=5)]
        public DateTime ExpiryDate
        {
            get
            {
                return this.expiryDateField;
            }
            set
            {
                this.expiryDateField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool ExpiryDateSpecified
        {
            get
            {
                return this.expiryDateFieldSpecified;
            }
            set
            {
                this.expiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("ProviderAssociations", Form=XmlSchemaForm.Unqualified, Order=6)]
        public AssociationRecordStructure[] ProviderAssociations
        {
            get
            {
                return this.providerAssociationsField;
            }
            set
            {
                this.providerAssociationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public partial class BSaddressStructure
    {
        
        private AONstructure sAONField;
        
        private AONstructure pAONField;
        
        private string streetDescriptionField;
        
        private string uniqueStreetReferenceNumberField;
        
        private string localityField;
        
        private string[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        private string postTownField;
        
        private string postCodeField;
        
        private string uniquePropertyReferenceNumberField;
        
        /// <remarks/>
        [XmlElement(Order=0)]
        public AONstructure SAON
        {
            get
            {
                return this.sAONField;
            }
            set
            {
                this.sAONField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=1)]
        public AONstructure PAON
        {
            get
            {
                return this.pAONField;
            }
            set
            {
                this.pAONField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=2)]
        public string StreetDescription
        {
            get
            {
                return this.streetDescriptionField;
            }
            set
            {
                this.streetDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="integer", Order=3)]
        public string UniqueStreetReferenceNumber
        {
            get
            {
                return this.uniqueStreetReferenceNumberField;
            }
            set
            {
                this.uniqueStreetReferenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=4)]
        public string Locality
        {
            get
            {
                return this.localityField;
            }
            set
            {
                this.localityField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("AdministrativeArea", typeof(string), Order=5)]
        [XmlElement("Town", typeof(string), Order=5)]
        [XmlChoiceIdentifier("ItemsElementName")]
        public string[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("ItemsElementName", Order=6)]
        [XmlIgnore()]
        public ItemsChoiceType[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=7)]
        public string PostTown
        {
            get
            {
                return this.postTownField;
            }
            set
            {
                this.postTownField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=8)]
        public string PostCode
        {
            get
            {
                return this.postCodeField;
            }
            set
            {
                this.postCodeField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="integer", Order=9)]
        public string UniquePropertyReferenceNumber
        {
            get
            {
                return this.uniquePropertyReferenceNumberField;
            }
            set
            {
                this.uniquePropertyReferenceNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [XmlType(Namespace="http://www.govtalk.gov.uk/people/bs7666", IncludeInSchema=false)]
    public enum ItemsChoiceType
    {
        
        /// <remarks/>
        AdministrativeArea,
        
        /// <remarks/>
        Town,
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://www.govtalk.gov.uk/people/PersonDescriptives")]
    public partial class PersonNameStructure
    {
        
        private string[] personNameTitleField;
        
        private string[] personGivenNameField;
        
        private string personFamilyNameField;
        
        private string[] personNameSuffixField;
        
        private string personRequestedNameField;
        
        /// <remarks/>
        [XmlElement("PersonNameTitle", Order=0)]
        public string[] PersonNameTitle
        {
            get
            {
                return this.personNameTitleField;
            }
            set
            {
                this.personNameTitleField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("PersonGivenName", Order=1)]
        public string[] PersonGivenName
        {
            get
            {
                return this.personGivenNameField;
            }
            set
            {
                this.personGivenNameField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=2)]
        public string PersonFamilyName
        {
            get
            {
                return this.personFamilyNameField;
            }
            set
            {
                this.personFamilyNameField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("PersonNameSuffix", Order=3)]
        public string[] PersonNameSuffix
        {
            get
            {
                return this.personNameSuffixField;
            }
            set
            {
                this.personNameSuffixField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=4)]
        public string PersonRequestedName
        {
            get
            {
                return this.personRequestedNameField;
            }
            set
            {
                this.personRequestedNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://ukrlp.co.uk.server.ws.v3")]
    public partial class AssociationRecordStructure
    {
        
        private string typeOfAssociationField;
        
        private string associationIdField;
        
        private string associationDescriptionField;
        
        private string associationStatusField;
        
        private DateTime associationCreatedDateField;
        
        private string associationMembershipStatusField;
        
        private DateTime associationMemberSinceDateField;
        
        private DateTime associationMembershipEndDateField;
        
        private bool associationMembershipEndDateFieldSpecified;
        
        private YesNoType leadProviderFlagField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public string TypeOfAssociation
        {
            get
            {
                return this.typeOfAssociationField;
            }
            set
            {
                this.typeOfAssociationField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, DataType="positiveInteger", Order=1)]
        public string AssociationId
        {
            get
            {
                return this.associationIdField;
            }
            set
            {
                this.associationIdField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=2)]
        public string AssociationDescription
        {
            get
            {
                return this.associationDescriptionField;
            }
            set
            {
                this.associationDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=3)]
        public string AssociationStatus
        {
            get
            {
                return this.associationStatusField;
            }
            set
            {
                this.associationStatusField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=4)]
        public DateTime AssociationCreatedDate
        {
            get
            {
                return this.associationCreatedDateField;
            }
            set
            {
                this.associationCreatedDateField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=5)]
        public string AssociationMembershipStatus
        {
            get
            {
                return this.associationMembershipStatusField;
            }
            set
            {
                this.associationMembershipStatusField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=6)]
        public DateTime AssociationMemberSinceDate
        {
            get
            {
                return this.associationMemberSinceDateField;
            }
            set
            {
                this.associationMemberSinceDateField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=7)]
        public DateTime AssociationMembershipEndDate
        {
            get
            {
                return this.associationMembershipEndDateField;
            }
            set
            {
                this.associationMembershipEndDateField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool AssociationMembershipEndDateSpecified
        {
            get
            {
                return this.associationMembershipEndDateFieldSpecified;
            }
            set
            {
                this.associationMembershipEndDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=8)]
        public YesNoType LeadProviderFlag
        {
            get
            {
                return this.leadProviderFlagField;
            }
            set
            {
                this.leadProviderFlagField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [XmlType(Namespace="http://www.govtalk.gov.uk/core")]
    public enum YesNoType
    {
        
        /// <remarks/>
        Yes,
        
        /// <remarks/>
        No,
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://ukrlp.co.uk.server.ws.v3")]
    public partial class authenticationDetails
    {
        
        private string userNameField;
        
        private string passwordField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://ukrlp.co.uk.server.ws.v3")]
    public partial class SelectionCriteriaStructure
    {
        
        private string[] unitedKingdomProviderReferenceNumberListField;
        
        private string[] providerNameListField;
        
        private string[] postcodeListField;
        
        private string searchTermField;
        
        private string basePostcodeField;
        
        private int maxDistanceFromBasePostcodeField;
        
        private bool maxDistanceFromBasePostcodeFieldSpecified;
        
        private DateTime providerUpdatedSinceField;
        
        private bool providerUpdatedSinceFieldSpecified;
        
        private DateTime providerVerifiedAfterField;
        
        private bool providerVerifiedAfterFieldSpecified;
        
        private DateTime providerVerifiedBeforeField;
        
        private bool providerVerifiedBeforeFieldSpecified;
        
        private QueryCriteriaConditionType criteriaConditionField;
        
        private bool criteriaConditionFieldSpecified;
        
        private string stakeholderIdField;
        
        private YesNoType approvedProvidersOnlyField;
        
        private bool approvedProvidersOnlyFieldSpecified;
        
        private string providerStatusField;
        
        /// <remarks/>
        [XmlArray(Form=XmlSchemaForm.Unqualified, Order=0)]
        [XmlArrayItem("UnitedKingdomProviderReferenceNumber", Form=XmlSchemaForm.Unqualified, DataType="positiveInteger", IsNullable=false)]
        public string[] UnitedKingdomProviderReferenceNumberList
        {
            get
            {
                return this.unitedKingdomProviderReferenceNumberListField;
            }
            set
            {
                this.unitedKingdomProviderReferenceNumberListField = value;
            }
        }
        
        /// <remarks/>
        [XmlArray(Form=XmlSchemaForm.Unqualified, Order=1)]
        [XmlArrayItem("ProviderName", Form=XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] ProviderNameList
        {
            get
            {
                return this.providerNameListField;
            }
            set
            {
                this.providerNameListField = value;
            }
        }
        
        /// <remarks/>
        [XmlArray(Form=XmlSchemaForm.Unqualified, Order=2)]
        [XmlArrayItem("Postcode", Form=XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] PostcodeList
        {
            get
            {
                return this.postcodeListField;
            }
            set
            {
                this.postcodeListField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=3)]
        public string SearchTerm
        {
            get
            {
                return this.searchTermField;
            }
            set
            {
                this.searchTermField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=4)]
        public string BasePostcode
        {
            get
            {
                return this.basePostcodeField;
            }
            set
            {
                this.basePostcodeField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=5)]
        public int MaxDistanceFromBasePostcode
        {
            get
            {
                return this.maxDistanceFromBasePostcodeField;
            }
            set
            {
                this.maxDistanceFromBasePostcodeField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool MaxDistanceFromBasePostcodeSpecified
        {
            get
            {
                return this.maxDistanceFromBasePostcodeFieldSpecified;
            }
            set
            {
                this.maxDistanceFromBasePostcodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=6)]
        public DateTime ProviderUpdatedSince
        {
            get
            {
                return this.providerUpdatedSinceField;
            }
            set
            {
                this.providerUpdatedSinceField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool ProviderUpdatedSinceSpecified
        {
            get
            {
                return this.providerUpdatedSinceFieldSpecified;
            }
            set
            {
                this.providerUpdatedSinceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=7)]
        public DateTime ProviderVerifiedAfter
        {
            get
            {
                return this.providerVerifiedAfterField;
            }
            set
            {
                this.providerVerifiedAfterField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool ProviderVerifiedAfterSpecified
        {
            get
            {
                return this.providerVerifiedAfterFieldSpecified;
            }
            set
            {
                this.providerVerifiedAfterFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=8)]
        public DateTime ProviderVerifiedBefore
        {
            get
            {
                return this.providerVerifiedBeforeField;
            }
            set
            {
                this.providerVerifiedBeforeField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool ProviderVerifiedBeforeSpecified
        {
            get
            {
                return this.providerVerifiedBeforeFieldSpecified;
            }
            set
            {
                this.providerVerifiedBeforeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=9)]
        public QueryCriteriaConditionType CriteriaCondition
        {
            get
            {
                return this.criteriaConditionField;
            }
            set
            {
                this.criteriaConditionField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool CriteriaConditionSpecified
        {
            get
            {
                return this.criteriaConditionFieldSpecified;
            }
            set
            {
                this.criteriaConditionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, DataType="integer", Order=10)]
        public string StakeholderId
        {
            get
            {
                return this.stakeholderIdField;
            }
            set
            {
                this.stakeholderIdField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=11)]
        public YesNoType ApprovedProvidersOnly
        {
            get
            {
                return this.approvedProvidersOnlyField;
            }
            set
            {
                this.approvedProvidersOnlyField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool ApprovedProvidersOnlySpecified
        {
            get
            {
                return this.approvedProvidersOnlyFieldSpecified;
            }
            set
            {
                this.approvedProvidersOnlyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=12)]
        public string ProviderStatus
        {
            get
            {
                return this.providerStatusField;
            }
            set
            {
                this.providerStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [XmlType(Namespace="http://www.ukrlp.gov.uk/commonlibrary")]
    public enum QueryCriteriaConditionType
    {
        
        /// <remarks/>
        AND,
        
        /// <remarks/>
        OR,
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [DebuggerStepThrough()]
    [XmlType(Namespace="http://ukrlp.co.uk.server.ws.v3")]
    public partial class ProviderQueryStructure
    {
        
        private SelectionCriteriaStructure selectionCriteriaField;
        
        private string queryIdField;
        
        private string schemaVersionField;
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
        public SelectionCriteriaStructure SelectionCriteria
        {
            get
            {
                return this.selectionCriteriaField;
            }
            set
            {
                this.selectionCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, DataType="integer", Order=1)]
        public string QueryId
        {
            get
            {
                return this.queryIdField;
            }
            set
            {
                this.queryIdField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute(DataType="token")]
        public string SchemaVersion
        {
            get
            {
                return this.schemaVersionField;
            }
            set
            {
                this.schemaVersionField = value;
            }
        }
    }
    
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [ServiceContract(Namespace="http://ukrlp.co.uk.server.ws.v3", ConfigurationName="Sfa.Tl.Matching.UkRlp.Api.Client.ProviderQueryPortType")]
    public interface ProviderQueryPortType
    {
        
        [OperationContract(Action="retrieveAllProviders", ReplyAction="*")]
        [FaultContract(typeof(faultDetail), Action="retrieveAllProviders", Name="faultDetail")]
        [XmlSerializerFormat(SupportFaults=true)]
        [ServiceKnownType(typeof(PersonMaritalStatusStructure))]
        [ServiceKnownType(typeof(PersonDeathDateStructure))]
        [ServiceKnownType(typeof(PersonBirthDateStructure))]
        [ServiceKnownType(typeof(AONrangeStructure))]
        [ServiceKnownType(typeof(BasicLandAndPropertyUnitStructure))]
        [ServiceKnownType(typeof(ProviderQueryResultStructure))]
        [ServiceKnownType(typeof(authenticationDetails))]
        Task<response> retrieveAllProvidersAsync(ProviderQueryParam request);
    }
    
    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [DebuggerStepThrough()]
    [XmlType(AnonymousType=true, Namespace="http://ukrlp.co.uk.server.ws.v3")]
    public partial class ProviderQueryResponse
    {
        
        private ProviderRecordStructure[] matchingProviderRecordsField;
        
        private string queryIdField;
        
        private string stakeholderIdField;
        
        /// <remarks/>
        [XmlElement("MatchingProviderRecords", Form=XmlSchemaForm.Unqualified, Order=0)]
        public ProviderRecordStructure[] MatchingProviderRecords
        {
            get
            {
                return this.matchingProviderRecordsField;
            }
            set
            {
                this.matchingProviderRecordsField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, DataType="integer", Order=1)]
        public string QueryId
        {
            get
            {
                return this.queryIdField;
            }
            set
            {
                this.queryIdField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified, DataType="integer", Order=2)]
        public string StakeholderId
        {
            get
            {
                return this.stakeholderIdField;
            }
            set
            {
                this.stakeholderIdField = value;
            }
        }
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [MessageContract(IsWrapped=false)]
    public partial class ProviderQueryParam
    {
        
        [MessageBodyMember(Namespace="http://ukrlp.co.uk.server.ws.v3", Order=0)]
        public ProviderQueryStructure ProviderQueryRequest;
        
        public ProviderQueryParam()
        {
        }
        
        public ProviderQueryParam(ProviderQueryStructure ProviderQueryRequest)
        {
            this.ProviderQueryRequest = ProviderQueryRequest;
        }
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [MessageContract(IsWrapped=false)]
    public partial class response
    {
        
        [MessageBodyMember(Namespace="http://ukrlp.co.uk.server.ws.v3", Order=0)]
        public ProviderQueryResponse ProviderQueryResponse;
        
        public response()
        {
        }
        
        public response(ProviderQueryResponse ProviderQueryResponse)
        {
            this.ProviderQueryResponse = ProviderQueryResponse;
        }
    }
    
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    public interface ProviderQueryPortTypeChannel : ProviderQueryPortType, IClientChannel
    {
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    public partial class ProviderQueryPortTypeClient : ClientBase<ProviderQueryPortType>, ProviderQueryPortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(ServiceEndpoint serviceEndpoint, ClientCredentials clientCredentials);
        
        public ProviderQueryPortTypeClient() : 
                base(GetDefaultBinding(), GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ProviderQueryPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProviderQueryPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(GetBindingForEndpoint(endpointConfiguration), GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProviderQueryPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GetBindingForEndpoint(endpointConfiguration), new EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProviderQueryPortTypeClient(EndpointConfiguration endpointConfiguration, EndpointAddress remoteAddress) : 
                base(GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProviderQueryPortTypeClient(Binding binding, EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        Task<response> ProviderQueryPortType.retrieveAllProvidersAsync(ProviderQueryParam request)
        {
            return base.Channel.retrieveAllProvidersAsync(request);
        }
        
        public Task<response> retrieveAllProvidersAsync(ProviderQueryStructure ProviderQueryRequest)
        {
            ProviderQueryParam inValue = new ProviderQueryParam();
            inValue.ProviderQueryRequest = ProviderQueryRequest;
            return ((ProviderQueryPortType)(this)).retrieveAllProvidersAsync(inValue);
        }
        
        public virtual Task OpenAsync()
        {
            return Task.Factory.FromAsync(((ICommunicationObject)(this)).BeginOpen(null, null), new Action<IAsyncResult>(((ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual Task CloseAsync()
        {
            return Task.Factory.FromAsync(((ICommunicationObject)(this)).BeginClose(null, null), new Action<IAsyncResult>(((ICommunicationObject)(this)).EndClose));
        }
        
        private static Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ProviderQueryPort))
            {
                BasicHttpBinding result = new BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ProviderQueryPort))
            {
                return new EndpointAddress("http://webservices.ukrlp.co.uk/UkrlpProviderQueryWS/ProviderQueryServiceV3");
            }
            throw new InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static Binding GetDefaultBinding()
        {
            return GetBindingForEndpoint(EndpointConfiguration.ProviderQueryPort);
        }
        
        private static EndpointAddress GetDefaultEndpointAddress()
        {
            return GetEndpointAddress(EndpointConfiguration.ProviderQueryPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ProviderQueryPort,
        }
    }
}