UPDATE ProviderVenue SET Postcode = 'TR1 3XX' WHERE Postcode = 'Tr1 3XX';
UPDATE ProviderVenue SET Postcode = 'BL1 6PQ' WHERE Postcode = 'bl1 6pq';
UPDATE ProviderVenue SET Postcode = 'CW5 6DF' WHERE Postcode = 'cw5 6df';
UPDATE ProviderVenue SET Postcode = 'DE6 1EP' WHERE Postcode = 'de61ep';
UPDATE ProviderVenue SET Postcode = 'TW5 0QR' WHERE Postcode = 'tw5 0qr';
UPDATE ProviderVenue SET Postcode = 'DL14 7JZ' WHERE Postcode = 'dl14 7jz';
UPDATE ProviderVenue SET Postcode = 'RG19 4LL' WHERE Postcode = 'rg19 4ll';
UPDATE ProviderVenue SET Postcode = 'LN4 1LH' WHERE Postcode = 'Ln4 1LH';
UPDATE ProviderVenue SET Postcode = 'NE5 2SZ' WHERE Postcode = 'ne52sz';
UPDATE ProviderVenue SET Postcode = 'S66 1JL' WHERE Postcode = 's66 1jl';
UPDATE ProviderVenue SET Postcode = 'B36 9HF' WHERE Postcode = 'b369hf';
UPDATE ProviderVenue SET Postcode = 'SK11 6QG' WHERE Postcode = 'sk116qg';
UPDATE ProviderVenue SET Postcode = 'CW7 3BS' WHERE Postcode = 'cw73bs';
UPDATE ProviderVenue SET Postcode = 'WA2 7TT' WHERE Postcode = 'wa27tt';
UPDATE ProviderVenue SET Postcode = 'CH1 4EE' WHERE Postcode = 'ch14ee';
UPDATE ProviderVenue SET Postcode = 'DE14 1NG' WHERE Postcode = 'de141ng';
UPDATE ProviderVenue SET Postcode = 'HD5 9PG' WHERE Postcode = 'Hd5 9PG';
UPDATE ProviderVenue SET Postcode = 'M43 7EU' WHERE Postcode = 'm43 7eu';
UPDATE ProviderVenue SET Postcode = 'W2 1NB' WHERE Postcode = 'w21NB';
UPDATE ProviderVenue SET Postcode = 'PE11 1WD' WHERE Postcode = 'pe11 1wd';
UPDATE ProviderVenue SET Postcode = 'NR1 1DL' WHERE Postcode = 'Nr1 1DL';
UPDATE ProviderVenue SET Postcode = 'RG21 8TN' WHERE Postcode = 'rg21 8tn';
UPDATE ProviderVenue SET Postcode = 'SW4 9BL' WHERE Postcode = 'Sw4 9BL';
UPDATE ProviderVenue SET Postcode = 'TS24 7NT' WHERE Postcode = 'ts24 7nt';
UPDATE ProviderVenue SET Postcode = 'RG4 9RH' WHERE Postcode = 'rg4 9rh';
UPDATE ProviderVenue SET Postcode = 'RG1 5AN' WHERE Postcode = 'rg1 5an';
UPDATE ProviderVenue SET Postcode = 'RG9 1EY' WHERE Postcode = 'rg91ey';
UPDATE ProviderVenue SET Postcode = 'RG9 1UH' WHERE Postcode = 'rg91uh';