UPDATE ProviderVenue SET Postcode = 'TR1 3XX' WHERE Postcode = 'Tr1 3XX'   COLLATE SQL_Latin1_General_CP1_CS_AS;
UPDATE ProviderVenue SET Postcode = 'BL1 6PQ' WHERE Postcode = 'bl1 6pq'   COLLATE SQL_Latin1_General_CP1_CS_AS;
UPDATE ProviderVenue SET Postcode = 'CW5 6DF' WHERE Postcode = 'cw5 6df'   COLLATE SQL_Latin1_General_CP1_CS_AS;
UPDATE ProviderVenue SET Postcode = 'DE6 1EP' WHERE Postcode = 'de61ep'    COLLATE SQL_Latin1_General_CP1_CS_AS;
UPDATE ProviderVenue SET Postcode = 'TW5 0QR' WHERE Postcode = 'tw5 0qr'   COLLATE SQL_Latin1_General_CP1_CS_AS;
UPDATE ProviderVenue SET Postcode = 'DL14 7JZ' WHERE Postcode = 'dl14 7jz' COLLATE SQL_Latin1_General_CP1_CS_AS;
UPDATE ProviderVenue SET Postcode = 'RG19 4LL' WHERE Postcode = 'rg19 4ll' COLLATE SQL_Latin1_General_CP1_CS_AS;
UPDATE ProviderVenue SET Postcode = 'LN4 1LH' WHERE Postcode = 'Ln4 1LH'   COLLATE SQL_Latin1_General_CP1_CS_AS;
UPDATE ProviderVenue SET Postcode = 'NE5 2SZ' WHERE Postcode = 'ne52sz'    COLLATE SQL_Latin1_General_CP1_CS_AS;
UPDATE ProviderVenue SET Postcode = 'S66 1JL' WHERE Postcode = 's66 1jl'   COLLATE SQL_Latin1_General_CP1_CS_AS;
UPDATE ProviderVenue SET Postcode = 'B36 9HF' WHERE Postcode = 'b369hf'    COLLATE SQL_Latin1_General_CP1_CS_AS;
UPDATE ProviderVenue SET Postcode = 'SK11 6QG' WHERE Postcode = 'sk116qg'  COLLATE SQL_Latin1_General_CP1_CS_AS;
UPDATE ProviderVenue SET Postcode = 'CW7 3BS' WHERE Postcode = 'cw73bs'    COLLATE SQL_Latin1_General_CP1_CS_AS;
UPDATE ProviderVenue SET Postcode = 'WA2 7TT' WHERE Postcode = 'wa27tt'    COLLATE SQL_Latin1_General_CP1_CS_AS;
UPDATE ProviderVenue SET Postcode = 'CH1 4EE' WHERE Postcode = 'ch14ee'    COLLATE SQL_Latin1_General_CP1_CS_AS;
UPDATE ProviderVenue SET Postcode = 'DE14 1NG' WHERE Postcode = 'de141ng'  COLLATE SQL_Latin1_General_CP1_CS_AS;
UPDATE ProviderVenue SET Postcode = 'HD5 9PG' WHERE Postcode = 'Hd5 9PG'   COLLATE SQL_Latin1_General_CP1_CS_AS;
UPDATE ProviderVenue SET Postcode = 'M43 7EU' WHERE Postcode = 'm43 7eu'   COLLATE SQL_Latin1_General_CP1_CS_AS;
UPDATE ProviderVenue SET Postcode = 'W2 1NB' WHERE Postcode = 'w21NB'      COLLATE SQL_Latin1_General_CP1_CS_AS;
UPDATE ProviderVenue SET Postcode = 'PE11 1WD' WHERE Postcode = 'pe11 1wd' COLLATE SQL_Latin1_General_CP1_CS_AS;
UPDATE ProviderVenue SET Postcode = 'NR1 1DL' WHERE Postcode = 'Nr1 1DL'   COLLATE SQL_Latin1_General_CP1_CS_AS;
UPDATE ProviderVenue SET Postcode = 'RG21 8TN' WHERE Postcode = 'rg21 8tn' COLLATE SQL_Latin1_General_CP1_CS_AS;
UPDATE ProviderVenue SET Postcode = 'SW4 9BL' WHERE Postcode = 'Sw4 9BL'   COLLATE SQL_Latin1_General_CP1_CS_AS;
UPDATE ProviderVenue SET Postcode = 'TS24 7NT' WHERE Postcode = 'ts24 7nt' COLLATE SQL_Latin1_General_CP1_CS_AS;
UPDATE ProviderVenue SET Postcode = 'RG4 9RH' WHERE Postcode = 'rg4 9rh'   COLLATE SQL_Latin1_General_CP1_CS_AS;
UPDATE ProviderVenue SET Postcode = 'RG1 5AN' WHERE Postcode = 'rg1 5an'   COLLATE SQL_Latin1_General_CP1_CS_AS;
UPDATE ProviderVenue SET Postcode = 'RG9 1EY' WHERE Postcode = 'rg91ey'    COLLATE SQL_Latin1_General_CP1_CS_AS;
UPDATE ProviderVenue SET Postcode = 'RG9 1UH' WHERE Postcode = 'rg91uh'    COLLATE SQL_Latin1_General_CP1_CS_AS;